package main

import (
	"sort"
	"strings"
)

// The socket verbs beyond the four the client carried.
//
// docs/SPEC-WORK.md's verbs block (the fenced block under "The verbs") is the
// list: "Session verbs run the process; every other verb is a client verb
// addressed to a session by `--session <path>` (required; no default)". The
// client reached four of them -- session start, session status, session stop
// and query -- so every other thing the kernel really keeps (nodes, states,
// roadmaps, axes, cells, renders, undo and redo plans, machines, events,
// dependency edges) was real to a Lisp test and to nobody at a shell.
//
// This file is the rest of that block. It adds no behaviour of its own: a
// socket verb IS its flag surface, since the client is thin by the spec's own
// rule -- "The values travel as the caller spelled them and the session
// validates every one" -- so a verb is one row of verbFlags plus its name in
// socketVerbs, and sessionVerb already spells the request line and classifies
// the reply.
//
// EVERY ROW BELOW IS READ OUT OF THE SPEC, NOT WRITTEN BESIDE IT.
// specverbs_test.go parses the same fenced block and fails if the two differ
// in a verb, a flag, an order or a flag's kind, so this table cannot drift
// from the document that defines it and a new flag in the spec is a red test
// rather than a silent gap.
//
// Four of the block's lines are deliberately NOT here, each for a reason the
// test knows by name:
//
//   - `state load` and `savepoint restore` are read-only local processes, not
//     client verbs: they take no --session, start no daemon and take no
//     ownership ("isolated and read-only" on both lines). They belong to a
//     reader this client does not yet carry.
//   - `report` is SPEC-AHEAD (#854) and has no kernel symbol at all; building
//     its client half first would be the spec growing a second time.
//   - `clip` COLLIDES: the spec's `clip --session <path> --as <name>
//     --git-timeout <seconds>` is a long operation on the resident session,
//     and `nova-work clip --worktree <dir> --branch <name> --base <ref>
//     --harvest <dir>` already ships as a local git verb of the swarm. One
//     name, two verbs, and nothing in the spec says which wins. That is a
//     question for the section's owners and not a thing to decide in a table.

// socketVerbs is every verb this client addresses to a resident session,
// beyond the four already in verbFlags, in the spec block's own order. The
// order is the order help prints and the order the request line spells.
var socketVerbs = []string{
	"session export",
	"session replay",
	"session handoff",
	"operation status",
	"operation list",
	"operation wait",
	"operation cancel",
	"savepoint list",
	"savepoint create",
	"savepoint verify",
	"savepoint compare",
	"undo-plan",
	"undo",
	"redo-plan",
	"redo",
	"friend",
	"config",
	"model",
	"observe",
	"goal set",
	"goal show",
	"goal update",
	"machine",
	"route",
	"offer",
	"profile",
	"acknowledge",
	"decline",
	"execution pause",
	"execution stop",
	"execution resume",
	"execution correct",
	"execution reconcile",
	"execution status",
	"check",
	"verify",
	"render",
	"node add",
	"node edit",
	"node move",
	"node remove",
	"node require",
	"decompose",
	"accept",
	"source",
	"dep",
	"axis",
	"roadmap create",
	"roadmap configure",
	"roadmap row",
	"roadmap projection",
	"prioritise",
	"cell",
	"responsible",
	"take",
	"heartbeat",
	"release",
	"attest",
	"attempt",
	"evidence",
	"state",
	"correct",
	"event",
}

func init() {
	for verb, specs := range moreVerbFlags {
		verbFlags[verb] = specs
	}
}

// moreVerbFlags is socketVerbs' flag surface, each verb's flags in the spec
// line's own order, so the request line a session reads is spelled the way its
// own document names the flags.
var moreVerbFlags = map[string][]flagSpec{
	"session export": {
		{name: "session"},
		{name: "journal"},
		{name: "max-bytes"},
		{name: "max-depth"},
		{name: "max-nodes"},
		{name: "into"},
		{name: "snapshot"},
		{name: "cache"},
		{name: "state", bool: true},
		{name: "at"},
		{name: "closed-history"},
		{name: "from"},
		{name: "to"},
		{name: "max-output-bytes"},
	},
	"session replay": {
		{name: "session"},
		{name: "from"},
		{name: "as"},
		{name: "max"},
	},
	"session handoff": {
		{name: "session"},
		{name: "to"},
		{name: "git-timeout"},
		{name: "attempts"},
	},
	"operation status": {
		{name: "session"},
		{name: "id"},
	},
	"operation list": {
		{name: "session"},
		{name: "max"},
	},
	"operation wait": {
		{name: "session"},
		{name: "id"},
		{name: "timeout"},
		{name: "after"},
	},
	"operation cancel": {
		{name: "session"},
		{name: "as"},
		{name: "request"},
		{name: "expect"},
		{name: "now"},
		{name: "deadline"},
		{name: "dry-run", bool: true},
		{name: "id"},
		{name: "reason"},
	},
	"savepoint list": {
		{name: "session"},
		{name: "max"},
	},
	"savepoint create": {
		{name: "session"},
		{name: "as"},
		{name: "reason"},
	},
	"savepoint verify": {
		{name: "session"},
		{name: "id"},
	},
	"savepoint compare": {
		{name: "savepoint"},
		{name: "against"},
		{name: "session"},
		{name: "snapshot"},
		{name: "max-bytes"},
		{name: "max-depth"},
		{name: "max-nodes"},
		{name: "max"},
	},
	"undo-plan": {
		{name: "session"},
		{name: "request"},
		{name: "max"},
	},
	"undo": {
		{name: "session"},
		{name: "as"},
		{name: "request"},
		{name: "expect"},
		{name: "now"},
		{name: "deadline"},
		{name: "dry-run", bool: true},
		{name: "request-of"},
		{name: "reason"},
	},
	"redo-plan": {
		{name: "session"},
		{name: "request"},
		{name: "max"},
	},
	"redo": {
		{name: "session"},
		{name: "as"},
		{name: "request"},
		{name: "expect"},
		{name: "now"},
		{name: "deadline"},
		{name: "dry-run", bool: true},
		{name: "request-of"},
		{name: "reason"},
	},
	"friend": {
		{name: "session"},
		{name: "as"},
		{name: "request"},
		{name: "expect"},
		{name: "now"},
		{name: "deadline"},
		{name: "dry-run", bool: true},
		{name: "register"},
		{name: "retire"},
		{name: "role"},
		{name: "participation"},
		{name: "capability"},
		{name: "group"},
		{name: "limit"},
		{name: "reason"},
	},
	"config": {
		{name: "session"},
		{name: "request"},
		{name: "base"},
		{name: "export"},
		{name: "into"},
		{name: "intake", bool: true},
		{name: "from"},
		{name: "as"},
		{name: "expect"},
		{name: "now"},
		{name: "deadline"},
		{name: "dry-run", bool: true},
		{name: "max"},
	},
	"model": {
		{name: "session"},
		{name: "as"},
		{name: "request"},
		{name: "expect"},
		{name: "now"},
		{name: "deadline"},
		{name: "dry-run", bool: true},
		{name: "register"},
		{name: "provider"},
		{name: "route"},
		{name: "billing"},
		{name: "rate"},
		{name: "effective"},
		{name: "source"},
		{name: "evidence"},
		{name: "task-class"},
		{name: "result"},
		{name: "samples"},
		{name: "reason"},
	},
	"observe": {
		{name: "session"},
		{name: "as"},
		{name: "request"},
		{name: "expect"},
		{name: "now"},
		{name: "deadline"},
		{name: "dry-run", bool: true},
		{name: "friend"},
		{name: "state"},
		{name: "source"},
		{name: "attempt"},
		{name: "observed-model"},
		{name: "bench"},
		{name: "usage"},
		{name: "reason"},
	},
	"goal set": {
		{name: "session"},
		{name: "as"},
		{name: "request"},
		{name: "expect"},
		{name: "now"},
		{name: "deadline"},
		{name: "dry-run", bool: true},
		{name: "scope"},
		{name: "goal"},
		{name: "clear", bool: true},
		{name: "reason"},
	},
	"goal show": {
		{name: "session"},
		{name: "snapshot"},
		{name: "max-bytes"},
		{name: "max-depth"},
		{name: "max-nodes"},
		{name: "cache"},
		{name: "as"},
		{name: "scope"},
		{name: "max"},
	},
	"goal update": {
		{name: "session"},
		{name: "as"},
		{name: "request"},
		{name: "expect"},
		{name: "now"},
		{name: "deadline"},
		{name: "dry-run", bool: true},
		{name: "scope"},
		{name: "progress"},
		{name: "evidence"},
		{name: "criterion"},
		{name: "against"},
		{name: "blocked-by"},
		{name: "reason"},
		{name: "stop", bool: true},
	},
	"machine": {
		{name: "session"},
		{name: "as"},
		{name: "request"},
		{name: "expect"},
		{name: "now"},
		{name: "deadline"},
		{name: "dry-run", bool: true},
		{name: "register"},
		{name: "name"},
		{name: "owner"},
		{name: "connect"},
		{name: "role"},
		{name: "retire"},
		{name: "permit"},
		{name: "exclude"},
		{name: "limit"},
		{name: "fact"},
		{name: "declared-by"},
		{name: "reason"},
	},
	"route": {
		{name: "session"},
		{name: "as"},
		{name: "request"},
		{name: "expect"},
		{name: "now"},
		{name: "deadline"},
		{name: "dry-run", bool: true},
		{name: "register"},
		{name: "provider"},
		{name: "endpoint"},
		{name: "key-location"},
		{name: "plan"},
		{name: "cost-per-mtok"},
		{name: "capabilities"},
		{name: "owner"},
		{name: "retire"},
		{name: "probe"},
		{name: "card"},
		{name: "pass"},
		{name: "wall"},
		{name: "usd"},
		{name: "source"},
		{name: "reason"},
	},
	"offer": {
		{name: "session"},
		{name: "as"},
		{name: "request"},
		{name: "expect"},
		{name: "now"},
		{name: "deadline"},
		{name: "dry-run", bool: true},
		{name: "node"},
		{name: "offer"},
		{name: "to"},
		{name: "profile"},
		{name: "attempt"},
		{name: "generation"},
		{name: "request-ref"},
		{name: "payload"},
		{name: "payload-sha256"},
		{name: "reserve"},
		{name: "until"},
		{name: "requested-model"},
		{name: "predecessor-offer"},
		{name: "predecessor-attempt"},
		{name: "reason"},
	},
	"profile": {
		{name: "session"},
		{name: "as"},
		{name: "request"},
		{name: "expect"},
		{name: "now"},
		{name: "deadline"},
		{name: "dry-run", bool: true},
		{name: "write"},
		{name: "model"},
		{name: "harness"},
		{name: "work-type"},
		{name: "pointer"},
		{name: "policy"},
		{name: "evidence"},
		{name: "expiry"},
		{name: "owner"},
		{name: "edit"},
		{name: "reason"},
	},
	"acknowledge": {
		{name: "session"},
		{name: "as"},
		{name: "request"},
		{name: "expect"},
		{name: "now"},
		{name: "deadline"},
		{name: "dry-run", bool: true},
		{name: "offer"},
		{name: "reply"},
		{name: "stage"},
		{name: "provenance"},
		{name: "provenance-sha256"},
		{name: "by"},
		{name: "default"},
		{name: "observed-model"},
		{name: "bench"},
		{name: "execution"},
		{name: "reason"},
	},
	"decline": {
		{name: "session"},
		{name: "as"},
		{name: "request"},
		{name: "expect"},
		{name: "now"},
		{name: "deadline"},
		{name: "dry-run", bool: true},
		{name: "offer"},
		{name: "reply"},
		{name: "provenance"},
		{name: "provenance-sha256"},
		{name: "reason"},
	},
	"execution pause": {
		{name: "session"},
		{name: "as"},
		{name: "request"},
		{name: "expect"},
		{name: "now"},
		{name: "deadline"},
		{name: "dry-run", bool: true},
		{name: "node"},
		{name: "repo"},
		{name: "all", bool: true},
		{name: "reason"},
	},
	"execution stop": {
		{name: "session"},
		{name: "as"},
		{name: "request"},
		{name: "expect"},
		{name: "now"},
		{name: "deadline"},
		{name: "dry-run", bool: true},
		{name: "node"},
		{name: "repo"},
		{name: "all", bool: true},
		{name: "reason"},
	},
	"execution resume": {
		{name: "session"},
		{name: "as"},
		{name: "request"},
		{name: "expect"},
		{name: "now"},
		{name: "deadline"},
		{name: "dry-run", bool: true},
		{name: "control"},
		{name: "action"},
		{name: "reason"},
	},
	"execution correct": {
		{name: "session"},
		{name: "as"},
		{name: "request"},
		{name: "expect"},
		{name: "now"},
		{name: "deadline"},
		{name: "dry-run", bool: true},
		{name: "node"},
		{name: "instructions"},
		{name: "sha256"},
		{name: "reason"},
	},
	"execution reconcile": {
		{name: "session"},
		{name: "as"},
		{name: "request"},
		{name: "expect"},
		{name: "now"},
		{name: "deadline"},
		{name: "dry-run", bool: true},
		{name: "control"},
		{name: "from"},
		{name: "reason"},
	},
	"execution status": {
		{name: "session"},
		{name: "control"},
		{name: "max"},
	},
	"check": {
		{name: "session"},
		{name: "snapshot"},
		{name: "max-bytes"},
		{name: "max-depth"},
		{name: "max-nodes"},
		{name: "cache"},
		{name: "max"},
	},
	"verify": {
		{name: "session"},
		{name: "offline", bool: true},
		{name: "max-fetch"},
		{name: "fetch-timeout"},
		{name: "node"},
		{name: "max"},
	},
	"render": {
		{name: "session"},
		{name: "view"},
		{name: "chat", bool: true},
		{name: "projection"},
		{name: "row-axis"},
		{name: "column-axis"},
		{name: "fixed", multi: true},
		{name: "file", bool: true},
		{name: "check", bool: true},
		{name: "at"},
	},
	"node add": {
		{name: "session"},
		{name: "as"},
		{name: "request"},
		{name: "expect"},
		{name: "now"},
		{name: "deadline"},
		{name: "dry-run", bool: true},
		{name: "id"},
		{name: "type"},
		{name: "under"},
		{name: "under-root"},
		{name: "repo"},
		{name: "title"},
		{name: "category"},
		{name: "required"},
		{name: "acceptance", multi: true},
		{name: "link", multi: true},
		{name: "links-empty", bool: true},
		{name: "clear-links", bool: true},
		{name: "private"},
		{name: "version"},
		{name: "reason"},
	},
	"node edit": {
		{name: "session"},
		{name: "as"},
		{name: "request"},
		{name: "expect"},
		{name: "now"},
		{name: "deadline"},
		{name: "dry-run", bool: true},
		{name: "node"},
		{name: "title"},
		{name: "clear-title", bool: true},
		{name: "category"},
		{name: "clear-category", bool: true},
		{name: "link", multi: true},
		{name: "links-empty", bool: true},
		{name: "clear-links", bool: true},
		{name: "private"},
		{name: "clear-private", bool: true},
		{name: "version"},
		{name: "clear-version", bool: true},
		{name: "reason"},
	},
	"node move": {
		{name: "session"},
		{name: "as"},
		{name: "request"},
		{name: "expect"},
		{name: "now"},
		{name: "deadline"},
		{name: "dry-run", bool: true},
		{name: "node"},
		{name: "from"},
		{name: "under"},
		{name: "reason"},
	},
	"node remove": {
		{name: "session"},
		{name: "as"},
		{name: "request"},
		{name: "expect"},
		{name: "now"},
		{name: "deadline"},
		{name: "dry-run", bool: true},
		{name: "node"},
		{name: "reason"},
	},
	"node require": {
		{name: "session"},
		{name: "as"},
		{name: "request"},
		{name: "expect"},
		{name: "now"},
		{name: "deadline"},
		{name: "dry-run", bool: true},
		{name: "node"},
		{name: "to"},
		{name: "reason"},
	},
	"decompose": {
		{name: "session"},
		{name: "as"},
		{name: "request"},
		{name: "expect"},
		{name: "now"},
		{name: "deadline"},
		{name: "dry-run", bool: true},
		{name: "node"},
		{name: "into"},
		{name: "acceptance", multi: true},
		{name: "reason"},
	},
	"accept": {
		{name: "session"},
		{name: "as"},
		{name: "request"},
		{name: "expect"},
		{name: "now"},
		{name: "deadline"},
		{name: "dry-run", bool: true},
		{name: "node"},
		{name: "add"},
		{name: "remove"},
		{name: "reason"},
	},
	"source": {
		{name: "session"},
		{name: "as"},
		{name: "request"},
		{name: "expect"},
		{name: "now"},
		{name: "deadline"},
		{name: "dry-run", bool: true},
		{name: "node"},
		{name: "to"},
		{name: "reason"},
	},
	"dep": {
		{name: "session"},
		{name: "as"},
		{name: "request"},
		{name: "expect"},
		{name: "now"},
		{name: "deadline"},
		{name: "dry-run", bool: true},
		{name: "node"},
		{name: "add"},
		{name: "remove"},
		{name: "reason"},
	},
	"axis": {
		{name: "session"},
		{name: "as"},
		{name: "request"},
		{name: "expect"},
		{name: "now"},
		{name: "deadline"},
		{name: "dry-run", bool: true},
		{name: "roadmap"},
		{name: "axis"},
		{name: "add"},
		{name: "remove"},
		{name: "reason"},
	},
	"roadmap create": {
		{name: "session"},
		{name: "as"},
		{name: "request"},
		{name: "expect"},
		{name: "now"},
		{name: "deadline"},
		{name: "dry-run", bool: true},
		{name: "id"},
		{name: "under"},
		{name: "title"},
		{name: "row-kind"},
		{name: "aggregation"},
		{name: "completion-policy"},
		{name: "axes-none", bool: true},
		{name: "axis-id", multi: true},
		{name: "permit-root", multi: true},
		{name: "reason"},
	},
	"roadmap configure": {
		{name: "session"},
		{name: "as"},
		{name: "request"},
		{name: "expect"},
		{name: "now"},
		{name: "deadline"},
		{name: "dry-run", bool: true},
		{name: "roadmap"},
		{name: "row-kind"},
		{name: "aggregation"},
		{name: "completion-policy"},
		{name: "axes-none", bool: true},
		{name: "axis-id", multi: true},
		{name: "permit-root", multi: true},
		{name: "roots-empty", bool: true},
		{name: "reason"},
	},
	"roadmap row": {
		{name: "session"},
		{name: "as"},
		{name: "request"},
		{name: "expect"},
		{name: "now"},
		{name: "deadline"},
		{name: "dry-run", bool: true},
		{name: "roadmap"},
		{name: "add"},
		{name: "remove"},
		{name: "reason"},
	},
	"roadmap projection": {
		{name: "session"},
		{name: "as"},
		{name: "request"},
		{name: "expect"},
		{name: "now"},
		{name: "deadline"},
		{name: "dry-run", bool: true},
		{name: "roadmap"},
		{name: "add"},
		{name: "root"},
		{name: "repo"},
		{name: "path"},
		{name: "start"},
		{name: "end"},
		{name: "policy"},
		{name: "row-axis"},
		{name: "column-axis"},
		{name: "fixed", multi: true},
		{name: "remove"},
		{name: "reason"},
	},
	"prioritise": {
		{name: "session"},
		{name: "as"},
		{name: "request"},
		{name: "expect"},
		{name: "now"},
		{name: "deadline"},
		{name: "dry-run", bool: true},
		{name: "node"},
		{name: "set"},
		{name: "clear", bool: true},
		{name: "context"},
		{name: "reason"},
	},
	"cell": {
		{name: "session"},
		{name: "as"},
		{name: "request"},
		{name: "expect"},
		{name: "now"},
		{name: "deadline"},
		{name: "dry-run", bool: true},
		{name: "roadmap"},
		{name: "coord"},
		{name: "ref"},
		{name: "out-of-scope", bool: true},
		{name: "in-scope", bool: true},
		{name: "reason"},
	},
	"responsible": {
		{name: "session"},
		{name: "as"},
		{name: "request"},
		{name: "expect"},
		{name: "now"},
		{name: "deadline"},
		{name: "dry-run", bool: true},
		{name: "node"},
		{name: "to"},
		{name: "reason"},
	},
	"take": {
		{name: "session"},
		{name: "as"},
		{name: "request"},
		{name: "expect"},
		{name: "now"},
		{name: "deadline"},
		{name: "dry-run", bool: true},
		{name: "node"},
		{name: "by"},
		{name: "default"},
	},
	"heartbeat": {
		{name: "session"},
		{name: "as"},
		{name: "request"},
		{name: "expect"},
		{name: "now"},
		{name: "deadline"},
		{name: "dry-run", bool: true},
		{name: "node"},
		{name: "evidence"},
		{name: "allocation"},
		{name: "generation"},
	},
	"release": {
		{name: "session"},
		{name: "as"},
		{name: "request"},
		{name: "expect"},
		{name: "now"},
		{name: "deadline"},
		{name: "dry-run", bool: true},
		{name: "node"},
		{name: "handed"},
		{name: "by"},
		{name: "default"},
		{name: "allocation"},
		{name: "generation"},
	},
	"attest": {
		{name: "session"},
		{name: "as"},
		{name: "request"},
		{name: "expect"},
		{name: "now"},
		{name: "deadline"},
		{name: "dry-run", bool: true},
		{name: "node"},
		{name: "criterion"},
		{name: "result"},
		{name: "against"},
	},
	"attempt": {
		{name: "session"},
		{name: "as"},
		{name: "request"},
		{name: "expect"},
		{name: "now"},
		{name: "deadline"},
		{name: "dry-run", bool: true},
		{name: "node"},
		{name: "model"},
		{name: "bench"},
		{name: "result"},
		{name: "usage"},
	},
	"evidence": {
		{name: "session"},
		{name: "as"},
		{name: "request"},
		{name: "expect"},
		{name: "now"},
		{name: "deadline"},
		{name: "dry-run", bool: true},
		{name: "node"},
		{name: "pointer"},
		{name: "criterion"},
		{name: "against"},
		{name: "attempt"},
	},
	"state": {
		{name: "session"},
		{name: "as"},
		{name: "request"},
		{name: "expect"},
		{name: "now"},
		{name: "deadline"},
		{name: "dry-run", bool: true},
		{name: "node"},
		{name: "to"},
		{name: "evidence", multi: true},
		{name: "reason"},
		{name: "blocked-by"},
	},
	"correct": {
		{name: "session"},
		{name: "as"},
		{name: "request"},
		{name: "expect"},
		{name: "now"},
		{name: "deadline"},
		{name: "dry-run", bool: true},
		{name: "node"},
		{name: "reason"},
	},
	"event": {
		{name: "session"},
		{name: "as"},
		{name: "request"},
		{name: "expect"},
		{name: "now"},
		{name: "deadline"},
		{name: "dry-run", bool: true},
		{name: "kind"},
		{name: "node"},
		{name: "reason"},
		{name: "member"},
		{name: "superseded-by"},
		{name: "evidence"},
	},
}

// verbFamilies are the first words that take a sub-verb, mapped to the
// sub-verbs the spec gives them. A family named with no sub-verb, or with one
// the spec does not spell, is refused naming the ones there are, rather than
// dialling a session with a request line no session can answer.
var verbFamilies = map[string][]string{}

func init() {
	for _, v := range allSocketVerbs() {
		head, sub, ok := strings.Cut(v, " ")
		if !ok {
			continue
		}
		verbFamilies[head] = append(verbFamilies[head], sub)
	}
	for head := range verbFamilies {
		sort.Strings(verbFamilies[head])
	}
}

// allSocketVerbs is every verb the client sends over the socket: the four that
// were already in verbFlags and socketVerbs' own. query is not here: it has a
// verb function of its own because the spec gives it constraints the client
// can check without the session (docs/SPEC-WORK.md, the query verb's own
// parenthetical), and run dispatches it by name.
func allSocketVerbs() []string {
	out := make([]string, 0, len(socketVerbs)+4)
	out = append(out, "session start", "session status", "session stop", "query")
	out = append(out, socketVerbs...)
	sort.Strings(out)
	return out
}

// resolveSocketVerb reads the verb off the front of the command line. A verb
// is one or two words and never more, so the longer spelling is tried first:
// `state` is a mutation verb and `state load` is a different thing entirely,
// and reading one as the other would send a load's flags to the mutation.
func resolveSocketVerb(head string, rest []string) (verb string, args []string, ok bool) {
	if len(rest) > 0 {
		if two := head + " " + rest[0]; verbFlags[two] != nil {
			return two, rest[1:], true
		}
	}
	if verbFlags[head] != nil && head != "query" {
		return head, rest, true
	}
	return "", nil, false
}

// notCarried names the block's lines this client does not send, so a caller
// who types one is told what it is rather than "unknown verb". The reason is
// the one in this file's header, said in one line.
var notCarried = map[string]string{
	"state load":        "`state load` reads an export directory into a new read-only session: it starts no daemon and takes no ownership, so it is a local reader and not a request to a session. This client does not carry it yet",
	"savepoint restore": "`savepoint restore` opens a savepoint into a new read-only session: isolated, taking no ownership and dispatching nothing, so it is a local reader and not a request to a session. This client does not carry it yet",
	"report":            "`report` is marked SPEC-AHEAD (nova-tools#854) in docs/SPEC-WORK.md and no session answers it yet",
}
