package main

import (
	"testing"
)

// budgetSeconds is the two-minute rule's working number: a package answers in a
// minute. Two minutes is the ceiling, not the target, so the recorded file is
// checked against the target and a package that crosses it is a red here rather
// than a slow CI nobody times.
const budgetSeconds = 60.0

// TestFastSuiteUnderOneMinute reads docs/TEST-DURATIONS.md -- the recorded
// measurement, regenerated by `go test -json -count=1 ./... | go run ./tools/testdur`
// -- and fails when a package's total crosses the budget ON THE BUDGET BENCH. It
// checks the RECORD, not the clock: a test that timed the suite here would be the
// slowest test in the repo, and a bench under load would make it flap. The record
// is what a person updates, so crossing the budget is a deliberate act with a red
// beside it.
//
// The record now holds more than one bench (benches_test.go says why only one of
// them is the budget's), so the rows are read through readRecord and the ones
// enforced here are the budget bench's alone.
func TestFastSuiteUnderOneMinute(t *testing.T) {
	rows, benches, _ := readRecord(t)
	budget := budgetBench(t, benches)
	checked := 0
	for _, r := range rows {
		if r.bench != budget {
			continue
		}
		checked++
		if r.secs > budgetSeconds {
			t.Errorf("%s takes %.1fs on %s; the budget is %.0fs -- give the slow tests a sync point or move them behind `//go:build slow` (#516)",
				r.pkg, r.secs, budget, budgetSeconds)
		}
	}
	if checked == 0 {
		t.Fatalf("%s holds no package rows for %s; the measurement was not recorded", durationsPath(), budget)
	}
}
