package main

import (
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"testing"
)

// budgetSeconds is the two-minute rule's working number: a package answers in a
// minute. Two minutes is the ceiling, not the target, so the recorded file is
// checked against the target and a package that crosses it is a red here rather
// than a slow CI nobody times.
const budgetSeconds = 60.0

// TestFastSuiteUnderOneMinute reads docs/TEST-DURATIONS.md -- the recorded
// measurement, regenerated by `go test -json -count=1 ./... | go run ./tools/testdur`
// -- and fails when a package's total crosses the budget. It checks the RECORD, not
// the clock: a test that timed the suite here would be the slowest test in the repo,
// and a bench under load would make it flap. The record is what a person updates, so
// crossing the budget is a deliberate act with a red beside it.
func TestFastSuiteUnderOneMinute(t *testing.T) {
	path := filepath.Join("..", "..", "docs", "TEST-DURATIONS.md")
	raw, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("the recorded durations are missing: %v", err)
	}
	rows := 0
	for _, line := range strings.Split(string(raw), "\n") {
		// The table rows are `| <package> | <seconds> | <slowest test> |`; the header
		// and its dashes are the two rows whose second cell is not a number.
		cells := strings.Split(strings.Trim(strings.TrimSpace(line), "|"), "|")
		if len(cells) < 2 {
			continue
		}
		pkg := strings.TrimSpace(cells[0])
		secs, err := strconv.ParseFloat(strings.TrimSpace(cells[1]), 64)
		if err != nil {
			continue
		}
		rows++
		if secs > budgetSeconds {
			t.Errorf("%s takes %.1fs; the budget is %.0fs -- give the slow tests a sync point or move them behind `//go:build slow` (#516)", pkg, secs, budgetSeconds)
		}
	}
	if rows == 0 {
		t.Fatalf("%s holds no package rows; the measurement was not recorded", path)
	}
}
