package docs

// Catalog is the hand-written half of the agent map: one row per directory
// that the live tree is allowed to contain at the mapped layer. internal/docs
// walks the tree, fills purpose/guard/command from this table, and writes
// AGENTS.md pages. A test guard fails when the pages drift, when a mapped
// directory appears that has no row, or when a row names a directory that is gone.
//
// Adding a directory therefore costs a row here and `make map`. Forgetting
// either is a red test, not a silent hole in the map.

// DefaultCatalog is the master catalog for nova-tools.
var DefaultCatalog = []Entry{
	E(".github", "CI workflows and automation", "go test ./internal/ci", "make test"),
	E("assets", "static assets and schemas", "none", "none"),
	E("fleet", "fleet loop units and bench templates", "none", "none"),
	Page("cmd", "17 nova command-line tools", "nova-ci local", "make build"),
	Page("docs", "specs, guides, and proposals", "go test ./internal/docs", "go test ./internal/docs"),
	E("infra", "runner images and scripts", "none", "none"),
	Page("internal", "packages and libraries", "nova-ci local", "make test"),
	E("tla", "the TLA+ models of the state machines and their runners", "go test ./internal/tlc", "make tlc-test"),
	E("profiles", "the darwin sandbox profile template internal/sandbox embeds, and the check that measures it (tools/sandboxcheck)", "go test ./internal/sandbox", "go test ./internal/sandbox"),
	E("testdata", "shared test fixtures and data", "go test ./internal/ci", "make test"),
	Page("tools", "developer and bench tools", "nova-ci local", "make map"),

	// cmd/
	E("cmd/nova-bus", "messages between AIs over Redis streams: one stream per recipient under a consumer group, one log, pending until acked", "go test ./cmd/nova-bus", "go test ./cmd/nova-bus"),
	E("cmd/nova-friend", "what a friend runs to be part of the team: the wake loop over nova-bus, the beat to the sprint server, and the proof of life, as one launchd daemon", "go test ./cmd/nova-friend", "go test -tags functional ./cmd/nova-friend"),
	E("cmd/nova-cairn", "session checkpoints: a session's exact words kept as plain files, with an index and receipts", "go test ./cmd/nova-cairn", "go test ./cmd/nova-cairn"),
	E("cmd/nova-decide", "typed decisions with probabilities through a backend, recorded and calibrated against their outcomes", "go test ./cmd/nova-decide", "go test ./cmd/nova-decide"),
	E("cmd/nova-config", "permanent configuration store (Postgres), friends and machines, applied into Redis", "go test ./cmd/nova-config", "go test ./cmd/nova-config"),
	E("cmd/nova-check", "checks over markdown records and repositories: links, kernel budget, no-code, floors, corpus, hygiene, dogfood, spelling", "go test ./cmd/nova-check", "go test ./cmd/nova-check"),
	E("cmd/nova-doctor", "one command that says what is missing and how to fix it: every registered dependency check, exit by the worst", "go test ./cmd/nova-doctor", "go test ./cmd/nova-doctor"),
	E("cmd/nova-card", "writes a directory of pre-linted briefs from a ledger, a findings file or a tool's help, for nova-sprint add --brief-dir", "go test ./cmd/nova-card", "go test ./cmd/nova-card"),
	E("cmd/nova-ci", "CI slowtests budget and check CLI, and ci-ok's run receipt", "go test ./cmd/nova-ci", "go test ./cmd/nova-ci"),
	E("cmd/nova-local", "run local models: what an engine has, one model served at a chosen context, and a worker description nova-swarm accepts", "go test ./cmd/nova-local", "go test ./cmd/nova-local"),
	E("cmd/nova-fuse", "the ingestion fuse: a recorded decision to stop reading an untrusted source, checked before each read", "go test ./cmd/nova-fuse", "go test ./cmd/nova-fuse"),
	E("cmd/nova-memory", "memory indexing and search CLI", "go test ./cmd/nova-memory", "go test ./cmd/nova-memory"),
	E("cmd/nova-redis", "Redis instance owner: serve, scratch spill/recall, and fn load/check of the function library", "go test ./cmd/nova-redis", "go test ./cmd/nova-redis"),
	E("cmd/nova-sandbox", "OS-level process sandbox CLI", "go test ./cmd/nova-sandbox", "go test ./cmd/nova-sandbox"),
	E("cmd/nova-secrets", "zero-leak secrets store CLI", "go test ./cmd/nova-secrets", "go test ./cmd/nova-secrets"),
	E("cmd/nova-self-talk", "flags sentences where a writer passes a standing verdict on themselves", "go test ./cmd/nova-self-talk", "go test ./cmd/nova-self-talk"),
	E("cmd/nova-sprint", "the sprint table: four tables on nova-table, the moves between them, the coordinator's inbox, and the driver that plays the world", "go test ./cmd/nova-sprint", "go test ./cmd/nova-sprint"),
	E("cmd/nova-swarm", "native card runner, bench slot leases and card lint CLI", "go test ./cmd/nova-swarm", "go test ./cmd/nova-swarm"),
	E("cmd/nova-table", "tables of ordered sets, text and percentages over Redis", "go test ./cmd/nova-table", "go test ./cmd/nova-table"),
	E("cmd/nova-tokens", "token consumption metering and budgeting CLI", "go test ./cmd/nova-tokens", "go test ./cmd/nova-tokens"),
	E("cmd/nova-update", "binary release update CLI", "go test ./cmd/nova-update", "go test ./cmd/nova-update"),
	E("cmd/nova-up", "set nova up on one machine: plan every step, then apply, from nothing to a first sprint", "go test ./cmd/nova-up", "go test ./cmd/nova-up"),
	E("cmd/nova-version", "build identity and version CLI", "go test ./cmd/nova-version", "go test ./cmd/nova-version"),
	E("cmd/nova-work", "every issue of every repository of an organization in one tree file, imported read-only and verified field for field", "go test ./cmd/nova-work", "go test ./cmd/nova-work"),

	// internal/
	E("internal/atomicfile", "atomic file write: standard-library rename beside the target", "go test ./internal/atomicfile", "go test ./internal/atomicfile"),
	E("internal/bounded", "bounded readers and byte buffers", "go test ./internal/bounded", "go test ./internal/bounded"),
	E("internal/bench", "the one bench runner: copy a tree to a per-run directory on the Linux bench, run one command there under nice with the bench cache, remove the directory it made, fall back when the host does not answer", "go test ./internal/bench", "go test ./internal/bench"),
	E("internal/binstamp", "a binary file's stamp: a loop stops when its own binary was replaced", "go test ./internal/binstamp", "go test ./internal/binstamp"),
	E("internal/buildinfo", "binary identity and version info", "go test ./internal/buildinfo", "go test ./internal/buildinfo"),
	E("internal/bus", "the message bus over Redis streams: the rules (send, recv, ack, peek, log) over a Store of the few commands used, the Redis store and the in-memory fake", "go test ./internal/bus", "go test -tags functional ./internal/bus"),
	E("internal/card", "what a brief's writers hold every brief to before it leaves: PATHS computed from its START files, and the card checks", "go test ./internal/card", "go test ./internal/card"),
	E("internal/cardgen", "nova-card's planner: ledger rows, findings and help to cards with PATHS, waves and the brief, pure over text", "go test ./internal/cardgen", "go test ./internal/cardgen"),
	E("internal/cairn", "the cairn store: session records, entries, the index and receipts, nested and flat", "go test ./internal/cairn", "go test ./internal/cairn"),
	E("internal/cardcontract", "the frame around a card's task: the frame file, JOB.md, the result shape, and the shims of each model family's profile", "go test ./internal/cardcontract", "go test -tags functional ./internal/cardcontract"),
	E("internal/cardcost", "what a card cost: a route's price sheet, a run's tokens by class, the predicted cost and a consumer card's usage record, in exact decimal arithmetic", "go test ./internal/cardcost", "go test ./internal/cardcost"),
	E("internal/cardlimits", "a card brief's refusal bound and the lint's size advice: two constants, no dependencies", "go test ./internal/cardlimits", "go test ./internal/cardlimits"),
	E("internal/cardtree", "a card as a tree of steps: the step grammar, its lint, the script step the member runs with no model, the verdict per step and the remainder of a failed step", "go test ./internal/cardtree", "go test ./internal/cardtree"),
	E("internal/cardhdr", "card header vocabulary and one-invariant lint", "go test ./internal/cardhdr", "go test ./internal/cardhdr"),
	E("internal/check", "the record checks: attest, links, kernel, nocode, floors, corpus, spelling", "go test ./internal/check", "go test ./internal/check"),
	E("internal/ci", "class tests and CI budget invariants", "go test ./internal/ci", "go test ./internal/ci"),
	E("internal/cireceipt", "ci-ok's run receipt: one ev:github row of the workflow_run shape", "go test ./internal/cireceipt", "go test -tags functional ./internal/cireceipt"),
	E("internal/config", "nova-config library: kind descriptors, the Postgres store and history, apply into Redis, the Ansible inventory of the applied state", "go test ./internal/config", "go test ./internal/config"),
	E("internal/converge", "convergence state and progress math", "go test ./internal/converge", "go test ./internal/converge"),
	E("internal/decide", "nova-decide's decision system: schemas (read, attempt, grade), backends (Jev, fixed), the record and calibration", "go test ./internal/decide", "go test ./internal/decide"),
	E("internal/diffcheck", "the lander's mechanical checks of a card's diff: files outside PATHS, stranded fragments", "go test ./internal/diffcheck", "go test ./internal/diffcheck"),
	E("internal/delayproxy", "a TCP proxy that holds each write of its clients back by a fixed delay: a store at a distance, made on the loopback, for testredis.Far and tools/fardelay", "go test ./internal/delayproxy", "go test ./internal/delayproxy"),
	E("internal/doctor", "nova-doctor frame: check registry, Env, results, and one check file per dependency", "go test ./internal/doctor", "go test ./internal/doctor"),
	E("internal/docs", "documentation guards and map generator", "go test ./internal/docs", "go test ./internal/docs"),
	E("internal/dogfood", "dogfood self-test gates", "go test ./internal/dogfood", "go test ./internal/dogfood"),
	E("internal/filelock", "process-exclusive file locks whose holder is named in the file", "go test ./internal/filelock", "go test ./internal/filelock"),
	E("internal/fleet", "runner fleet discovery and status", "go test ./internal/fleet", "go test ./internal/fleet"),
	E("internal/friend", "nova-friend's rules apart from the transport: the connection and challenge machine with an injected clock, the daemon loop over the bus, the deliver adapters per harness, the state files and the launchd agent", "go test ./internal/friend", "go test ./internal/friend"),
	E("internal/fuse", "the fuse box: read and write the lockdown and quarantine state", "go test ./internal/fuse", "go test ./internal/fuse"),
	Page("internal/ghevent", "the GitHub event Redis stream: append and read", "go test ./internal/ghevent", "go test ./internal/ghevent"),
	E("internal/ghevent/wire", "shared GitHub event stream identity without ingestion dependencies", "go test ./internal/ci", "go test ./internal/ci"),
	E("internal/gitrun", "the one runner for a one-shot git child: a deadline, WaitDelay and the caller's environment choice", "go test ./internal/gitrun", "go test ./internal/gitrun"),
	E("internal/harness", "the harness words: opencode and the headless subscription harnesses of the heavy tier", "go test ./internal/harness", "go test ./internal/harness"),
	E("internal/gocache", "Go build cache held under a size, least recently used first", "go test ./internal/gocache", "go test ./internal/gocache"),
	E("internal/goenv", "Go environment scrubber for child processes", "go test ./internal/goenv", "go test ./internal/goenv"),
	E("internal/hostload", "a machine's load: CPU busy percent of all its cores, else the load average over them", "go test ./internal/hostload", "go test ./internal/hostload"),
	E("internal/hygiene", "clean checkout and leak assertions", "go test ./internal/hygiene", "go test ./internal/hygiene"),
	E("internal/keyshape", "cryptographic key format verification", "go test ./internal/keyshape", "go test ./internal/keyshape"),
	E("internal/layout", "the one place every derived path comes from: the machine's nova_root and the roots under it", "go test ./internal/layout", "go test ./internal/layout"),
	E("internal/log", "structured logging helpers", "go test ./internal/log", "go test ./internal/log"),
	E("internal/memindex", "memory vector and text index", "go test ./internal/memindex", "go test ./internal/memindex"),
	E("internal/nsprint", "the shared Redis store and login, its Functions, and the verb flags the living tools use", "go test ./internal/nsprint/...", "go test ./internal/nsprint/..."),
	E("internal/nogh", "the refusing gh command installed first on child shell PATHs", "go test ./internal/nogh", "go test ./internal/nogh"),
	E("internal/ntable", "a general Redis-backed table: ordered sets per cell, projections, folds, the render", "go test ./internal/ntable", "go test ./internal/ntable"),
	E("internal/onboarding", "onboarding banner and doc verifier", "go test ./internal/onboarding", "go test ./internal/onboarding"),
	E("internal/oneline", "single-line log and output grammar", "go test ./internal/oneline", "go test ./internal/oneline"),
	E("internal/pkgselect", "package selection, the shard deal and the test fan-out that CI and nova-ci local share", "go test ./internal/pkgselect", "go test ./internal/pkgselect"),
	E("internal/provbalance", "a model provider's balance read through the seat's key", "go test ./internal/provbalance", "go test ./internal/provbalance"),
	E("internal/record", "decision and execution records", "go test ./internal/record", "go test ./internal/record"),
	E("internal/readregular", "the one way to read a file a tool did not write: regular files only (links followed), size capped, FIFOs and devices refused by name", "go test ./internal/readregular", "go test ./internal/readregular"),
	E("internal/redisconn", "the one way a nova tool opens its Redis connection: options from the environment, one bounded dial, trips counted, errors classified, no secret shown", "go test ./internal/redisconn", "go test ./internal/redisconn"),
	E("internal/redisacl", "the fleet store's ACL users rendered from the function library and the key families, and compared with a store's live ACL", "go test ./internal/redisacl", "go test ./internal/redisacl"),
	E("internal/redisfn", "build, load and check a Redis function library from embedded Lua source", "go test ./internal/redisfn", "go test ./internal/redisfn"),
	E("internal/release", "release packaging and manifest gates", "go test ./internal/release", "go test ./internal/release"),
	E("internal/safepath", "path sanitization and sandboxing", "go test ./internal/safepath", "go test ./internal/safepath"),
	E("internal/sandbox", "OS isolation primitives (seatbelt/landlock)", "go test ./internal/sandbox", "go test ./internal/sandbox"),
	E("internal/scaffold", "scaffolding engine for class rules and CLI verbs", "go test ./internal/scaffold", "go test ./internal/scaffold"),
	E("internal/secrets", "zero-leak memory and file vault", "go test ./internal/secrets", "go test ./internal/secrets"),
	E("internal/seatcred", "a seat's Redis login read through the secrets library (--seat, NOVA_SEAT)", "go test ./internal/seatcred/...", "go test ./internal/seatcred/..."),
	E("internal/selftalk", "agent self-talk journal stream", "go test ./internal/selftalk", "go test ./internal/selftalk"),
	E("internal/shippedsmoke", "the smoke test of a shipped nova-check binary, behind the shippedsmoke build tag, run by the certification workflow", "go test -tags shippedsmoke ./internal/shippedsmoke", "NOVA_SHIPPED_BIN=<binary> go test -tags shippedsmoke -v ./internal/shippedsmoke"),
	E("internal/sprint", "the sprint table's pure core (lifecycle, steps, check, inbox) and its binding to the table layer (store) and its driver (play)", "go test ./internal/sprint/...", "go test ./internal/sprint/..."),
	E("internal/member", "a sprint fleet member's loop: beat, queue, push and judge the finish, take to width, each card a child", "go test ./internal/member", "go test ./internal/member"),
	E("internal/sprintdash", "the sprint dashboard (nova-sprint dashboard): the page embedded in the binary, a cached copy of where --json, and the check that holds the page equal to docs/SPEC-SPRINT-DASHBOARD.md", "go test ./internal/sprintdash", "go test ./internal/sprintdash"),
	E("internal/sprintwire", "how a worker talks to the sprint's server (nova-sprint run --listen): the request and reply of a batch of verbs, the client, and the member's sprint over it", "go test ./internal/sprintwire", "go test ./internal/sprintwire"),
	E("internal/subproc", "the one door a child process goes through: a named deadline per kind, WaitDelay, and a cancellable context for long-lived children", "go test ./internal/subproc", "go test ./internal/subproc"),
	E("internal/swarm", "the native card runner: staging, the wall, budgets, slot leases and card lint", "go test ./internal/swarm", "go test ./internal/swarm"),
	E("internal/testbin", "places a built program into a test dir", "go test ./internal/testbin", "go test ./internal/testbin"),
	E("internal/testgit", "the one git identity for tests that commit in a scratch repository, and the hosted runner's identity-less git for reproducing it", "go test ./internal/testgit", "go test ./internal/testgit"),
	E("internal/testguard", "host seam and leak interception", "go test ./internal/testguard", "go test ./internal/testguard"),
	E("internal/testkit", "test rigs shared by every package: a tool's entry point run in process with both streams captured, and the files a test writes and reads", "go test ./internal/testkit", "go test ./internal/testkit"),
	E("internal/testredis", "a throwaway redis-server for one test: loopback only, nothing kept, never outlives its test binary; Far puts a store at a distance", "go test ./internal/testredis", "go test ./internal/testredis"),
	E("internal/testverbhelp", "per-tool check that every verb answers -h at exit 0 and touches nothing", "go test ./internal/testverbhelp", "go test ./internal/testverbhelp"),
	E("internal/tablemodel", "the table model's checks: the suites, the finding witnesses and the receipt replay against EpochMemberTable", "go test ./internal/tablemodel", "go test -tags functional ./internal/tablemodel"),
	E("internal/textbody", "shared line-oriented message body filtering", "go test ./internal/textbody", "go test ./internal/textbody"),
	E("internal/tlc", "TLC runner: the jar, the run, its results read, the case plan and the run records", "go test ./internal/tlc", "go test ./internal/tlc"),
	E("internal/tool", "the one shape of a command: verbs, banner, help, version, refusals, and the output envelope rendered as lines or JSON", "go test ./internal/tool", "go test ./internal/tool"),
	E("internal/tokens", "token counter and budget tracker", "go test ./internal/tokens", "go test ./internal/tokens"),
	E("internal/tty", "whether a file is a terminal and how large its screen is", "go test ./internal/tty", "go test ./internal/tty"),
	E("internal/typedrec", "typed RESULT record contract, its format and the disposition line", "go test ./internal/typedrec", "go test ./internal/typedrec"),
	E("internal/units", "the text and install of every unit a running sprint needs: a launchd agent or systemd user unit per kind, written by a verb and loaded through the caller's loader", "go test ./internal/units", "go test ./internal/units"),
	E("internal/update", "binary updater and checksum verifier", "go test ./internal/update", "go test ./internal/update"),
	E("internal/up", "nova-up's steps: the registry, the plan and apply of each step over a fake-able machine", "go test ./internal/up", "go test ./internal/up"),
	E("internal/workfile", "nova-work tree file: the model, its canonical writer, strict reader and field-for-field diff", "go test ./internal/workfile", "go test ./internal/workfile"),
	E("internal/workgh", "nova-work read-only GitHub issue capture over GraphQL, every call counted", "go test ./internal/workgh", "go test ./internal/workgh"),
	E("internal/worklang", "bounded reader for nova-work's restricted s-expression tree file", "go test ./internal/worklang", "go test ./internal/worklang"),
	E("internal/yield", "CI over work: a copy, a local test run or a sprint card's native launch steps itself to nice 15 before it execs (nova-tools#4293)", "go test ./internal/yield", "go test ./internal/yield"),

	// docs/
	E("docs/acceptance", "release acceptance records: one measured requirement per file, with the raw numbers", "go test ./internal/ci", "go test ./internal/ci -run TestAcceptanceRecordsAreWellFormed"),
	E("docs/audit", "cold audit records of the codebase, one directory per auditor and date: numbered issues with file:line, evidence, a grade and a fix", "go test ./internal/docs", "go test ./internal/docs"),
	E("docs/dogfood", "dated dogfood records of the tools, one file per tool and run: every verb used cold, every finding graded", "go test ./internal/docs", "go test ./internal/docs"),
	E("docs/fixtures", "doc examples and test fixtures", "go test ./internal/docs", "go test ./internal/docs"),
	E("docs/nova-config", "nova-config guide: the permanent configuration and its apply into Redis", "go test ./internal/docs", "go test ./internal/docs"),
	E("docs/nova-table", "nova-table guide: the design statement, the keys, the verbs, the render rules", "go test ./internal/docs", "go test ./internal/docs"),
	E("docs/sprint", "the nova-sprint 1.0.0 glossary, which moves to nova-sprint's docs/ at the split", "go test ./internal/docs", "go test ./internal/docs -run TestRetiredWordsAppearOnlyInRecords"),
	E("docs/ratings", "cold ratings of the tools, one file per rater and tool", "go test ./internal/docs", "go test ./internal/docs"),
	E("docs/stranger", "cold stranger runs of the tools, one file per run, every stumble with its proposed card", "go test ./internal/docs", "go test ./internal/docs"),

	// tools/
	E("tools/agentsmap", "AGENTS.md map generator CLI", "go test ./internal/docs", "make map"),
	E("tools/analyzers", "vetlaw verb-law analyzers", "go test ./tools/analyzers/...", "make vet-laws"),
	E("tools/benchstandard", "the Linux bench's acceptance witness: one DRIFT line per finding against the standard, STANDARD OK or STANDARD DRIFT, and --apply kills stray runner listeners and nothing else", "go test ./tools/benchstandard", "go run ./tools/benchstandard"),
	E("tools/ci", "the verbs CI and the Makefile call: package selection and the shard deal, the test-step checks, the ancestry fetch, gofmt, the redis, postgres and sbcl installs, the lisp tier, the job aggregates, revert-on-red and the run reports; one runner for every process", "go test ./tools/ci", "go run ./tools/ci help"),
	E("tools/clidoc", "CLI reference generator from tool help", "go test ./internal/docs", "make clidoc"),
	E("tools/fardelay", "a store at a distance as a process: a loopback proxy that holds each write of its clients back by a fixed delay", "go test ./tools/fardelay", "go run ./tools/fardelay --target HOST:PORT --delay 64ms"),
	E("tools/functionalrun", "the functional tier inside one container per run, and the reaper of its overdue containers", "go test ./tools/functionalrun", "make test-functional-container"),
	E("tools/ghrelease", "the GitHub release verbs: the stamped ldflags, the build of every shipped tool per platform, the checksums over the shipped set, the stamp assertion, the certified gate and the draft-only upload", "go test ./tools/ghrelease", "go run ./tools/ghrelease help"),
	E("tools/newrule", "class rule scaffolding CLI", "go test ./tools/newrule", "go test ./tools/newrule"),
	E("tools/newverb", "CLI verb scaffolding CLI", "go test ./tools/newverb", "go test ./tools/newverb"),
	E("tools/notes20261002", "the 2026-10-02 notes written into nova-config: the seed, as a Go program with the arguments and refusals of the script it replaced", "go test ./tools/notes20261002", "go run ./tools/notes20261002 <args>"),
	E("tools/preflight", "the standard check before a card or a pull request: gofmt, go vet and the unit tests through make test-full", "go test ./tools/preflight", "make preflight"),
	E("tools/sandboxcheck", "the darwin profile check of nova-sandbox: fills the profile template for a scratch write set and runs the first second of a job inside the wall, each denial beside a control outside it", "go test ./tools/sandboxcheck", "go run ./tools/sandboxcheck"),
	E("tools/sessiontrace", "bounded shell trace replay against TableSession", "go test ./tools/sessiontrace", "go test ./tools/sessiontrace"),
	E("tools/sprintsize", "nova-sprint's size run: the sprint at 10x its largest real size on a local store, each operation timed against its limit", "go vet ./tools/sprintsize", "go run ./tools/sprintsize --bin <nova-sprint>"),
	E("tools/tlacheck", "TLA+ model check CLI: run the declared cases, the table and member suites, the receipt replay and the finding witnesses", "go test ./tools/tlacheck", "go test ./tools/tlacheck"),
	E("tools/testmanifest", "exact named Go test manifest checker", "go test ./tools/testmanifest", "go test ./tools/testmanifest"),
}
