package docs

// Catalog is the hand-written half of the agent map: one row per directory
// that the live tree is allowed to contain at the mapped layer. internal/docs
// walks the tree, fills purpose/guard/command from this table, and writes
// AGENTS.md pages. A test guard fails when the pages drift, when a mapped
// directory appears that has no row, or when a row names a directory that is gone.
//
// Adding a directory therefore costs a row here and `make map`. Forgetting
// either is a red test, not a silent hole in the map.

// DefaultCatalog is the master catalog for nova-tools.
var DefaultCatalog = []Entry{
	E(".github", "CI workflows and automation", "go test ./internal/ci", "make test"),
	E("assets", "static assets and schemas", "none", "none"),
	E("fleet", "fleet loop units and bench templates", "none", "none"),
	Page("cmd", "22 nova command-line tools", "nova-ci local", "make build"),
	Page("docs", "specs, guides, and proposals", "go test ./internal/docs", "go test ./internal/docs"),
	E("infra", "runner images and scripts", "none", "none"),
	Page("internal", "packages and libraries", "nova-ci local", "make test"),
	E("tla", "the TLA+ models of the state machines and their runners", "tla/check_table.py, tla/check_member.py (each under a 120 s budget)", "none"),
	E("profiles", "the darwin sandbox profile template internal/sandbox embeds, and its check script", "go test ./internal/sandbox", "go test ./internal/sandbox"),
	E("deprecated", "tools and modules no longer in use, kept for reference only; never built, tested or maintained", "none", "none"),
	E("scripts", "maintenance and operational scripts", "none", "none"),
	E("testdata", "shared test fixtures and data", "go test ./internal/ci", "make test"),
	Page("tools", "developer and bench tools", "nova-ci local", "make map"),

	// cmd/
	E("cmd/nova-bus", "coordination bus inbox, send, and wait CLI", "go test ./cmd/nova-bus", "go test ./cmd/nova-bus"),
	E("cmd/nova-cairn", "dusk memory distillation CLI", "go test ./cmd/nova-cairn", "go test ./cmd/nova-cairn"),
	E("cmd/nova-config", "permanent configuration store (Postgres), friends and machines, applied into Redis", "go test ./cmd/nova-config", "go test ./cmd/nova-config"),
	E("cmd/nova-check", "codebase hygiene and constraint check CLI", "go test ./cmd/nova-check", "go test ./cmd/nova-check"),
	E("cmd/nova-ci", "CI slowtests budget and check CLI, and ci-ok's run receipt", "go test ./cmd/nova-ci", "go test ./cmd/nova-ci"),
	E("cmd/nova-fuse", "workspace isolation and boundary CLI", "go test ./cmd/nova-fuse", "go test ./cmd/nova-fuse"),
	E("cmd/nova-memory", "memory indexing and search CLI", "go test ./cmd/nova-memory", "go test ./cmd/nova-memory"),
	E("cmd/nova-post", "PR and issue posting CLI", "go test ./cmd/nova-post", "go test ./cmd/nova-post"),
	E("cmd/nova-redis", "Redis scratch spill/recall CLI", "go test ./cmd/nova-redis", "go test ./cmd/nova-redis"),
	E("cmd/nova-sandbox", "OS-level process sandbox CLI", "go test ./cmd/nova-sandbox", "go test ./cmd/nova-sandbox"),
	E("cmd/nova-secrets", "zero-leak secrets store CLI", "go test ./cmd/nova-secrets", "go test ./cmd/nova-secrets"),
	E("cmd/nova-self-talk", "internal dialogue recording CLI", "go test ./cmd/nova-self-talk", "go test ./cmd/nova-self-talk"),
	E("cmd/nova-sprint", "sprint dealer, table, and CI-card CLI", "go test ./cmd/nova-sprint", "go test ./cmd/nova-sprint"),
	E("cmd/nova-table", "a table over Redis, every cell an ordered set; the sprint's stream block is its first table", "go test ./cmd/nova-table", "go test ./cmd/nova-table"),
	E("cmd/nova-tokens", "token consumption metering and budgeting CLI", "go test ./cmd/nova-tokens", "go test ./cmd/nova-tokens"),
	E("cmd/nova-update", "binary release update CLI", "go test ./cmd/nova-update", "go test ./cmd/nova-update"),
	E("cmd/nova-version", "build identity and version CLI", "go test ./cmd/nova-version", "go test ./cmd/nova-version"),

	// internal/
	E("internal/atomicfile", "atomic file write: standard-library rename beside the target", "go test ./internal/atomicfile", "go test ./internal/atomicfile"),
	E("internal/bounded", "bounded readers and byte buffers", "go test ./internal/bounded", "go test ./internal/bounded"),
	E("internal/buildinfo", "binary identity and version info", "go test ./internal/buildinfo", "go test ./internal/buildinfo"),
	E("internal/bus", "append-only coordination bus", "go test ./internal/bus", "go test ./internal/bus"),
	E("internal/cairn", "memory distillation and cairn builder", "go test ./internal/cairn", "go test ./internal/cairn"),
	E("internal/cardhdr", "card header vocabulary and one-invariant lint", "go test ./internal/cardhdr", "go test ./internal/cardhdr"),
	E("internal/check", "hygiene rules and tree checkers", "go test ./internal/check", "go test ./internal/check"),
	E("internal/ci", "class tests and CI budget invariants", "go test ./internal/ci", "go test ./internal/ci"),
	E("internal/cireceipt", "ci-ok's run receipt: one ev:github row, the row nova-wake watch --store reads", "go test ./internal/cireceipt", "go test -tags functional ./internal/cireceipt"),
	E("internal/civerdict", "reader of a commit's CI verdict record", "go test ./internal/civerdict", "go test ./internal/civerdict"),
	E("internal/config", "nova-config library: kind descriptors, the Postgres store and history, apply into Redis", "go test ./internal/config", "go test ./internal/config"),
	E("internal/converge", "convergence state and progress math", "go test ./internal/converge", "go test ./internal/converge"),
	E("internal/ctxindex", "per-repo spec, test and symbol index for cards", "go test ./internal/ctxindex", "go test ./internal/ctxindex"),
	E("internal/decide", "criteria evaluation and decisions", "go test ./internal/decide", "go test ./internal/decide"),
	E("internal/docs", "documentation guards and map generator", "go test ./internal/docs", "go test ./internal/docs"),
	E("internal/dogfood", "dogfood self-test gates", "go test ./internal/dogfood", "go test ./internal/dogfood"),
	E("internal/events", "card event stream and SQLite fold", "go test ./internal/events", "go test ./internal/events"),
	E("internal/filelock", "process-exclusive file locks with holder stamps and state probing", "go test ./internal/filelock", "go test ./internal/filelock"),
	E("internal/fleet", "runner fleet discovery and status", "go test ./internal/fleet", "go test ./internal/fleet"),
	E("internal/fuse", "workspace isolation boundaries", "go test ./internal/fuse", "go test ./internal/fuse"),
	E("internal/gh", "the one GitHub client: every call counted per verb, one paced writer, events over polling (#4343)", "go test ./internal/gh", "go test ./internal/gh"),
	Page("internal/ghevent", "GitHub webhook to Redis stream", "go test ./internal/ghevent", "go test ./internal/ghevent"),
	E("internal/ghevent/testdata", "GitHub delivery fixtures for the decoder", "go test ./internal/ghevent", "go test ./internal/ghevent"),
	E("internal/ghevent/wire", "shared GitHub event stream identity without ingestion dependencies", "go test ./internal/ci", "go test -tags functional ./internal/gh ./internal/wake"),
	E("internal/goenv", "Go environment scrubber for child processes", "go test ./internal/goenv", "go test ./internal/goenv"),
	E("internal/hygiene", "clean checkout and leak assertions", "go test ./internal/hygiene", "go test ./internal/hygiene"),
	E("internal/jev", "Jev's mechanical passes (lint, scope, base) as one JEV gate line", "go test ./internal/jev", "go test ./internal/jev"),
	E("internal/jobs", "background job queues and state", "go test ./internal/jobs", "go test ./internal/jobs"),
	E("internal/keyshape", "cryptographic key format verification", "go test ./internal/keyshape", "go test ./internal/keyshape"),
	E("internal/lanes", "lane cursor and dispatch isolation", "go test ./internal/lanes", "go test ./internal/lanes"),
	E("internal/log", "structured logging helpers", "go test ./internal/log", "go test ./internal/log"),
	E("internal/memindex", "memory vector and text index", "go test ./internal/memindex", "go test ./internal/memindex"),
	E("internal/merge", "batch merge queue and land operations", "go test ./internal/merge", "go test ./internal/merge"),
	E("internal/metrics", "Prometheus surface shared by the queue verbs", "go test ./internal/metrics/...", "go test ./internal/metrics/..."),
	E("internal/nsprint", "nova-sprint dealer, store, fold, and table", "go test ./internal/nsprint/...", "go test ./internal/nsprint/..."),
	E("internal/ntable", "a general Redis-backed table: ordered sets per cell, projections, folds, the render", "go test ./internal/ntable", "go test ./internal/ntable"),
	E("internal/onboarding", "onboarding banner and doc verifier", "go test ./internal/onboarding", "go test ./internal/onboarding"),
	E("internal/oneline", "single-line log and output grammar", "go test ./internal/oneline", "go test ./internal/oneline"),
	E("internal/play", "sandboxed code experiment runner", "go test ./internal/play", "go test ./internal/play"),
	E("internal/post", "GitHub PR and issue client", "go test ./internal/post", "go test ./internal/post"),
	E("internal/presence", "friend heartbeat keys with a TTL", "go test ./internal/presence", "go test ./internal/presence"),
	E("internal/record", "decision and execution records", "go test ./internal/record", "go test ./internal/record"),
	E("internal/records", "database models and record formats", "go test ./internal/records", "go test ./internal/records"),
	E("internal/redisconn", "the one way a nova tool opens its Redis connection: options from the environment, one bounded dial, trips counted, errors classified, no secret shown", "go test ./internal/redisconn", "go test ./internal/redisconn"),
	E("internal/redisfn", "build, load and check a Redis function library from embedded Lua source", "go test ./internal/redisfn", "go test ./internal/redisfn"),
	E("internal/redisq", "Redis transport queue", "go test ./internal/redisq", "go test ./internal/redisq"),
	E("internal/release", "release packaging and manifest gates", "go test ./internal/release", "go test ./internal/release"),
	E("internal/safepath", "path sanitization and sandboxing", "go test ./internal/safepath", "go test ./internal/safepath"),
	E("internal/sandbox", "OS isolation primitives (seatbelt/landlock)", "go test ./internal/sandbox", "go test ./internal/sandbox"),
	E("internal/scaffold", "scaffolding engine for class rules and CLI verbs", "go test ./internal/scaffold", "go test ./internal/scaffold"),
	E("internal/secrets", "zero-leak memory and file vault", "go test ./internal/secrets", "go test ./internal/secrets"),
	E("internal/seatcred", "a seat's Redis login read through the secrets library (--seat, NOVA_SEAT)", "go test ./internal/seatcred/...", "go test ./internal/seatcred/..."),
	E("internal/selftalk", "agent self-talk journal stream", "go test ./internal/selftalk", "go test ./internal/selftalk"),
	E("internal/sprintline", "sprint x/y z% -> eta line", "go test ./internal/sprintline", "go test ./internal/sprintline"),
	E("internal/sprinttable", "sprint table publish and restart behaviour", "go test ./internal/sprinttable", "go test ./internal/sprinttable"),
	E("internal/swarm", "swarm worker pool and execution engine", "go test ./internal/swarm", "go test ./internal/swarm"),
	E("internal/testbin", "places a built program into a test dir", "go test ./internal/testbin", "go test ./internal/testbin"),
	E("internal/testguard", "host seam and leak interception", "go test ./internal/testguard", "go test ./internal/testguard"),
	E("internal/testpg", "a throwaway Postgres for one test or one package: loopback only, trust authentication, stopped with the test", "go test ./internal/testpg", "go test ./internal/testpg"),
	E("internal/testredis", "a throwaway redis-server for one test: loopback only, nothing kept, never outlives its test binary", "go test ./internal/testredis", "go test ./internal/testredis"),
	E("internal/textbody", "shared line-oriented message body filtering", "go test ./internal/textbody", "go test ./internal/textbody"),
	E("internal/tokens", "token counter and budget tracker", "go test ./internal/tokens", "go test ./internal/tokens"),
	E("internal/typedrec", "typed RESULT record contract, parser and legacy adapter", "go test ./internal/typedrec", "go test ./internal/typedrec"),
	E("internal/update", "binary updater and checksum verifier", "go test ./internal/update", "go test ./internal/update"),
	E("internal/wake", "slot leases and heartbeat monitors", "go test ./internal/wake", "go test ./internal/wake"),
	E("internal/worklang", "worklang s-expression evaluator", "go test ./internal/worklang", "go test ./internal/worklang"),
	E("internal/yield", "CI over work: a copy or local test run steps itself to nice 15 before it execs (nova-tools#4293)", "go test ./internal/yield", "go test ./internal/yield"),

	// docs/
	E("docs/spec-pulse", "the card contract the pulse cut engine writes (10-the-card-as-cut-writes-it.md); the rest of the spec folder deleted 2026-09-24", "go test ./internal/docs", "go test ./internal/docs"),
	E("docs/drafts", "in-flight design drafts and proposals", "go test ./internal/docs", "go test ./internal/docs"),
	E("docs/fixtures", "doc examples and test fixtures", "go test ./internal/docs", "go test ./internal/docs"),
	E("docs/jev", "Jev's versioned decision prompts, one file per type and version (#4316)", "go test ./internal/nsprint/jev", "go test ./internal/nsprint/jev"),
	E("docs/nova-config", "nova-config guide: the permanent configuration and its apply into Redis", "go test ./internal/docs", "go test ./internal/docs"),
	E("docs/nova-friend", "nova-friend guide: the presence process, the verbs, the keys it owns", "go test ./internal/docs", "go test ./internal/docs"),
	E("docs/nova-sprint", "nova-sprint verb guide", "go test ./internal/docs", "go test ./internal/docs"),
	E("docs/nova-table", "nova-table guide: the design statement, the keys, the verbs, the render rules", "go test ./internal/docs", "go test ./internal/docs"),
	E("docs/roadmaps", "sprint roadmaps and milestones", "go test ./internal/docs", "go test ./internal/docs"),
	E("docs/schemas", "event and payload schema definitions", "go test ./internal/docs", "go test ./internal/docs"),

	// tools/
	E("tools/agentsmap", "AGENTS.md map generator CLI", "go test ./internal/docs", "make map"),
	E("tools/analyzers", "vetlaw verb-law analyzers", "go test ./tools/analyzers/...", "make vet-laws"),
	E("tools/ci", "CI helper and build scripts", "go test ./internal/ci", "make test"),
	E("tools/newrule", "class rule scaffolding CLI", "go test ./tools/newrule", "go test ./tools/newrule"),
	E("tools/newverb", "CLI verb scaffolding CLI", "go test ./tools/newverb", "go test ./tools/newverb"),
	E("tools/testdur", "test duration analyzer and budget checker", "go test ./tools/testdur", "go test ./tools/testdur"),
	E("tools/testmanifest", "exact named Go test manifest checker", "go test ./tools/testmanifest", "go test ./tools/testmanifest"),
}
