package merge

import (
	"strings"
	"testing"
)

// TestReaderRuleIsPersonAndModelNotLogin is Glenn's ruling of 2026-09-23 (4:05-4:12 PM
// EDT; rowan-new memory/reader-is-a-different-model-not-a-different-login.md): the read
// rule exists only to put a DIFFERENT AI PERSON on a DIFFERENT MODEL, with a different
// point of view, on the code. The rowan-claude login is the mechanized harvest identity,
// not authorship. So the author a read is refused for is ReaderAuthor's PERSON, never the
// login:
//
//   - a harvest-opened swarm card (rowan/card-*, or a RESULT-line body) takes rowan's
//     typed APPROVE at head as its read;
//   - a Rowan-child PR (rowan/<task-id>, DONE-WHEN body) refuses rowan's and takes stella's;
//   - a Stella PR (stella/* on the shared login) refuses stella's and takes rowan's.
//
// Holds stay keyed by who=: the holder's own later APPROVE releases, and a who=unknown
// hold is released only by a reader who is not the author.
func TestReaderRuleIsPersonAndModelNotLogin(t *testing.T) {
	t.Parallel()

	rs, err := ParseReviewers(strings.NewReader("who\tlogins\tmay-hold\n" +
		"emma\tgafferongames\tyes\nstella\tgafferongames\tyes\njohnny\tgafferongames\tyes\n" +
		"glenn\tgafferongames\tyes\nrowan\trowan-claude\tyes\n"))
	if err != nil {
		t.Fatal(err)
	}
	head := strings.Repeat("a", 40)
	read := func(who, at string) Read {
		return Read{Who: who, Verdict: "approve", Head: head, At: at}
	}
	stand := func(pr PR, reads ...Read) (string, Standing) {
		a := ReaderAuthor(pr, rs)
		return a, EvaluateReads(&Entry{PR: pr.Number, OID: head, NeedsRead: "yes", Reads: reads}, a)
	}
	// who=unknown hold at head, released by a non-author may-hold reader's own HOLD record
	unknownHoldReleasedBy := func(pr PR, who string) bool {
		hold := Verdict{ID: "comment:1", Who: "unknown", Word: "hold", Head: head, At: "2026-09-23T20:00:00Z", Source: "comment-rule", Kind: "line"}
		rec := Read{Who: who, Verdict: "hold", Head: head, At: "2026-09-23T20:05:00Z"}
		return len(UnreleasedHolds([]Verdict{hold}, []Read{rec}, head, ReaderAuthor(pr, rs), rs)) == 0
	}

	t.Run("swarm card: rowan's typed read lands it", func(t *testing.T) {
		for _, pr := range []PR{
			{Number: 1, Author: "rowan-claude", HeadRef: "rowan/card-0412-fix-foo", Body: "harvest: card 0412"},
			{Number: 2, Author: "rowan-claude", HeadRef: "rowan/fix-nova-tools-2454-x",
				Body: "RESULT: CARD-0977 fix nova-tools 2454 OK\n\nSwarm card fix-nova-tools-2454 on hulk via nova-swarm native."},
			{Number: 3, Author: "rowan-claude", HeadRef: "rowan/card-0413",
				Body: "From nova-swarm card 413. RESULT.md:\n\n```\nRESULT: CARD-0413 OK\n```"},
			// every swarm branch shape, keyed on the branch and never the login (Glenn 4:50 PM)
			{Number: 6, Author: "rowan-claude", HeadRef: "rowan/fix3-land-7", Body: "harvest card"},
			{Number: 7, Author: "rowan-claude", HeadRef: "rowan/nx-0412"},
			{Number: 8, Author: "rowan-claude", HeadRef: "rowan/e0412-sweep"},
			{Number: 9, Author: "rowan-claude", HeadRef: "rowan/probe-rt268"},
			{Number: 10, Author: "gafferongames", HeadRef: "fix3-top-level"},
		} {
			a, st := stand(pr, read("rowan", "2026-09-23T20:00:00Z"))
			if a != "swarm" {
				t.Fatalf("#%d %s: ReaderAuthor = %q, want swarm (harvest's login is not authorship)", pr.Number, pr.HeadRef, a)
			}
			if !st.Satisfied || strings.Join(st.Approvers, ",") != "rowan" {
				t.Fatalf("#%d: rowan's APPROVE at head must satisfy a swarm card: %+v", pr.Number, st)
			}
			if !unknownHoldReleasedBy(pr, "rowan") {
				t.Fatalf("#%d: rowan is a non-author reader on a swarm card and may take over an unknown hold", pr.Number)
			}
		}
	})

	t.Run("rowan child PR: rowan's read refused, stella's lands it", func(t *testing.T) {
		pr := PR{Number: 4, Author: "rowan-claude", HeadRef: "rowan/fix-land-lane-reader-model-rule",
			Body: "DONE-WHEN: TestX fails before and passes after.\n\nGenerated by a Rowan child."}
		a, st := stand(pr, read("rowan", "2026-09-23T20:00:00Z"))
		if a != "rowan" {
			t.Fatalf("ReaderAuthor = %q, want rowan (a Rowan child's PR is Rowan's own)", a)
		}
		if st.Satisfied || len(st.Approvers) != 0 {
			t.Fatalf("rowan's own APPROVE must not satisfy a Rowan-child PR: %+v", st)
		}
		if unknownHoldReleasedBy(pr, "rowan") {
			t.Fatal("rowan is the author of a Rowan-child PR and must not take over an unknown hold on it")
		}
		_, st = stand(pr, read("rowan", "2026-09-23T20:00:00Z"), read("stella", "2026-09-23T20:05:00Z"))
		if !st.Satisfied || strings.Join(st.Approvers, ",") != "stella" {
			t.Fatalf("stella's APPROVE at head must satisfy it, rowan's not counted: %+v", st)
		}
	})

	t.Run("stella PR: stella's read refused, rowan's lands it", func(t *testing.T) {
		// Stella has no GitHub id (Glenn 4:50 PM): her PR is the stella/* branch, under
		// either login it comes through.
		for _, pr := range []PR{
			{Number: 5, Author: "gafferongames", HeadRef: "stella/some-fix", Body: "DONE-WHEN: TestY passes."},
			{Number: 11, Author: "rowan-claude", HeadRef: "stella/some-fix", Body: "DONE-WHEN: TestY passes."},
		} {
			stellaPR(t, pr, stand, unknownHoldReleasedBy)
		}
	})
}

func stellaPR(t *testing.T, pr PR, stand func(PR, ...Read) (string, Standing), unknownHoldReleasedBy func(PR, string) bool) {
	t.Helper()
	head := strings.Repeat("a", 40)
	read := func(who, at string) Read {
		return Read{Who: who, Verdict: "approve", Head: head, At: at}
	}
	a, st := stand(pr, read("stella", "2026-09-23T20:00:00Z"))
	if a != "stella" {
		t.Fatalf("#%d under %s: ReaderAuthor = %q, want stella (the branch names the person, never the login)", pr.Number, pr.Author, a)
	}
	if st.Satisfied {
		t.Fatalf("stella's own APPROVE must not satisfy her PR: %+v", st)
	}
	if unknownHoldReleasedBy(pr, "stella") {
		t.Fatal("stella is the author of her PR and must not take over an unknown hold on it")
	}
	_, st = stand(pr, read("stella", "2026-09-23T20:00:00Z"), read("rowan", "2026-09-23T20:05:00Z"))
	if !st.Satisfied || strings.Join(st.Approvers, ",") != "rowan" {
		t.Fatalf("rowan's APPROVE at head must satisfy a Stella PR: %+v", st)
	}
	if !unknownHoldReleasedBy(pr, "rowan") {
		t.Fatal("rowan is a non-author reader on a Stella PR")
	}
}
