;;;; package.lisp --- nova-work slice 1: the internal C/O transition kernel.
;;;;
;;;; Spec: docs/SPEC-WORK.md at 7db3b95cd4c16b1eb34b1c77c0fc224755cc7a64
;;;; (mas-bandwidth/nova-tools PR #231, branch spec/nova-work).
;;;;
;;;; This system is the internal kernel only. There is no session, no CLI, no
;;;; socket, no provider and no live import here; see README.md for the boundary.

(defpackage #:nova-work
  (:use #:common-lisp)
  (:export
   ;; conditions
   #:nova-work-error
   #:restricted-data-violation
   #:unsupported-input
   #:not-implemented
   #:journal-error
   #:journal-corrupt-data
   #:journal-corrupt-data-path
   #:journal-corrupt-data-offset
   #:journal-corrupt-data-reason
   #:journal-mismatch
   #:journal-mismatch-path
   #:journal-mismatch-what
   #:journal-sync-failed
   #:journal-sync-failed-path
   #:journal-sync-failed-reason
   #:journal-uncertain-write
   #:journal-uncertain-write-path
   #:journal-uncertain-write-reason
   ;; restricted data and canonical serialization
   #:+absent+
   #:absentp
   #:canonical-string
   #:canonical-print
   #:read-restricted
   ;; digest
   #:sha256-hex
   ;; events
   #:make-work-event
   #:work-event-kind
   #:work-event-node
   #:work-event-by
   #:work-event-fields
   #:work-event-stamp
   #:work-event-clock
   #:work-event-request
   #:work-event-generation-owner
   #:work-event-rev
   #:work-event-session-written-p
   #:event-digest-form
   #:event-record-form
   #:event-id
   #:closed-row-key
   #:payload-digest
   ;; state
   #:make-seed-state
   #:state-open-count
   #:state-closed-count
   #:state-revision
   #:state-history
   #:state-closed-rows
   #:node-open-count
   #:node-branch
   #:node-state
   #:node-coordinator
   #:node-required-count
   #:node-required-open
   #:node-deps
   #:node-needs-broken
   #:ready-p
   #:ready-nodes
   #:root-digest
   #:state-canonical-form
   #:reconstruct-state
   #:apply-event
   ;; instrumentation
   #:*visits* #:*parses* #:*replays*
   #:with-instrumentation
   ;; journal acceptance interface
   #:*before-apply-hook*
   #:journal-accept
   #:journal-record
   #:journal-lookup
   #:ordering-journal
   #:make-ordering-journal
   #:journal-order
   #:dedup-page-available-p
   #:rejecting-journal
   #:make-rejecting-journal
   #:journal-reject-on
   #:file-journal
   #:make-file-journal
   #:open-file-journal
   #:close-file-journal
   #:with-file-journal
   #:journal-fail-sync-on
   #:journal-fail-pre-write-on
   #:journal-fail-partial-write-on
   #:journal-fail-creation-sync-on
   #:replay-journal
   #:read-header
   #:read-record-frame
   #:journal-path
   #:journal-seq
   #:journal-uncertain-p
   #:sync-stream
   #:sync-directory
    ;; kernel
    #:make-kernel
    #:kernel-state
    #:kernel-journal
    #:kernel-next-rev
    #:submit
    #:ask-size
     #:open-issue-count
     #:open-leaf-count
    ;; state export / isolated load (SPEC-WORK.md:3273-3297, replays :5879-5905)
    #:export-state
    #:export-complete
    #:export-manifest
    #:state-export-id
    #:state-export-revision
    #:state-export-bytes
    #:state-export-members
    #:state-export-status
    #:state-export-terminal
    #:state-export-published
    #:publish-state-export
    #:cancel-state-export
    #:retention-pass
    #:load-state
    #:snapshot-state
    #:snapshot-revision
    #:snapshot-query
    #:snapshot-accept-session-p
    #:with-isolation
    #:isolation-count
    #:isolation-writes
    #:make-fenced-session
    #:fenced-export-start
    #:fenced-status
    #:fenced-cancel
    #:fenced-operation-list
    #:fenced-write
    #:fenced-claim
    ;; the fleet: static machine records in CONFIG (SPEC-WORK.md:3459-3588)
    #:make-fleet
    #:kernel-fleet
    #:fleet-friends
    #:fleet-machines
    #:fleet-order
    #:fleet-member
    #:fleet-members
    #:fleet-member-count
    #:machine
    #:machine-id
    #:machine-name
    #:machine-owner
    #:machine-connect
    #:machine-roles
    #:machine-permits
    #:machine-excludes
    #:machine-limits
    #:machine-facts
    ;; applicable/delegation replays (Go card 8132)
    #:note-id
    #:make-note
    #:candidate-role
    #:candidate-model
    #:constraint-p
    #:constraint-deny
    #:constraint-prefer
    #:constraint-reason
    #:deny-matches-p
    #:constraint-excludes-p
    #:applicable
    #:make-applicable-answer
    #:applicable-answer-p
    #:applicable-answer-rev
    #:applicable-answer-from
    #:applicable-answer-verdicts
    #:applicable-answer-notes
    #:applicable-answer-fail
    #:applicable-answer-shown
    #:applicable-answer-more
    #:verdict-eligible-p
    #:verdict-unknown-p
    #:verdict-planning-p
    #:verdict-excluded-p
    #:excluded-note-ids
    #:price-route
    #:route-selection
    #:build-card
    #:*delegation-packet-fields*
    #:delegation-admission
    #:gate-2-refusal
    #:gate-3-refusal
    #:admission
    #:admission-expect
    #:gate-4-refusal
    #:offer-to
    #:non-terminating-p
    #:uncertain-outcome-p
    #:retry-permitted-p
    #:make-execution-record
    #:execution-record-requested-limit
    #:execution-record-expiry
    #:execution-record-stop
    #:make-machinery-receipt
    #:machinery-receipt-head
    #:machinery-receipt-result
    #:book-receipt
    #:review-binds-p
    #:review-reusable-p
    ;; CONFIG roles (SPEC-WORK.md:5214)
    #:make-role-record
    #:role-record-id
    #:role-record-scope
    #:role-record-source
    #:role-record-reserved-for
    #:role-record-essential-security-only-p
    #:role-record-different-perspective-p
    #:role-record-participation-p
    #:role-record-limit
    #:make-role-config
    #:role-config-roles
    #:role-from-config
    #:role-inferred-from-model-p
    #:agreed-limit-for
    #:spend-role
    ;; config/availability replays (card 8627)
    #:make-availability
    #:availability-state
    #:availability-last-contact
    #:availability-reserved
    #:availability-silence-threshold
    #:availability-answer-window
    #:availability-pinged
    #:silence-breach-p
    #:silence-ping
    #:mark-pinged
    #:mark-unconfirmed
    #:make-return-reconciliation
    #:return-reconciliation-assignments
    #:return-reconciliation-capacity
    #:return-reconciliation-done
    #:reconcile-return
    #:return-done-p
    #:dispatch-gate
    #:fragment-digest
    #:*config-fragment-keys*
    #:*config-secret-keys*
    #:make-config
    #:config-hash
    #:config-identity
    #:config-fragment
    #:make-delta-entry
    #:config-delta
    #:config-request
    #:apply-config-delta
    #:manifest-digest
    #:make-manifest
    #:find-secret
    #:admit-manifest
    ;; fleet recommendation and the four assignment facts (Go card 8629)
    #:make-machine
    #:machine-id
    #:machine-name
    #:machine-owner
    #:machine-roles
    #:machine-permits
    #:machine-excludes
    #:machine-limits
    #:machine-facts
    #:machine-connect
    #:machine-excludes-p
    #:machine-admits-p
    #:make-fleet-session
    #:fleet-session-who
    #:fleet-session-leases
    #:make-fleet-ask
    #:fleet-ask-kind
    #:fleet-ask-rows
    #:fleet-ask-fail
    #:fleet-ask-lease
    #:fleet-ask-exit-code
    #:fleet-row
    #:fleet-for
    #:make-assignment-state
    #:assignment-state-who
    #:assignment-state-offers
    #:assignment-state-deliveries
    #:assignment-state-acceptances
    #:assignment-state-declines
    #:assignment-state-reservations
    #:assignment-state-leases
    #:assignment-state-attempts
    #:assignment-state-evidence
    #:assignment-state-completed
    #:assignment-state-node-state
    #:assignment-state-w
    #:assignment-state-responsible
    #:assignment-state-free-slots
    #:assignment-state-launches
    #:*session-written-fields*
    #:make-staged-input
    #:staged-input-bytes
    #:staged-input-result
    #:staged-input-valid-p
    #:staged-input-rev
    #:staged-input-reason
    #:stage-provenance
    #:session-written-field
    #:assignment-offer
    #:assignment-acknowledge
    #:assignment-decline
    #:session-status))

(defpackage #:nova-work/tests
  (:use #:common-lisp #:nova-work)
  (:export #:run-all #:main))
