;;;; package.lisp --- nova-work slice 1: the internal C/O transition kernel.
;;;;
;;;; Spec: docs/SPEC-WORK.md at 7db3b95cd4c16b1eb34b1c77c0fc224755cc7a64
;;;; (mas-bandwidth/nova-tools PR #231, branch spec/nova-work).
;;;;
;;;; This system is the internal kernel only. There is no session, no CLI, no
;;;; socket, no provider and no live import here; see README.md for the boundary.

(defpackage #:nova-work
  (:use #:common-lisp)
  (:export
   ;; conditions
   #:nova-work-error
   #:restricted-data-violation
   #:unsupported-input
   #:not-implemented
   #:journal-error
   #:journal-corrupt-data
   #:journal-corrupt-data-path
   #:journal-corrupt-data-offset
   #:journal-corrupt-data-reason
   #:journal-mismatch
   #:journal-mismatch-path
   #:journal-mismatch-what
   #:journal-sync-failed
   #:journal-sync-failed-path
   #:journal-sync-failed-reason
   #:journal-uncertain-write
   #:journal-uncertain-write-path
   #:journal-uncertain-write-reason
   ;; restricted data and canonical serialization
   #:+absent+
   #:absentp
   #:canonical-string
   #:canonical-print
   #:read-restricted
   ;; digest
   #:sha256-hex
   ;; events
   #:make-work-event
   #:work-event-kind
   #:work-event-node
   #:work-event-by
   #:work-event-fields
   #:work-event-stamp
   #:work-event-clock
   #:work-event-request
   #:work-event-generation-owner
   #:work-event-rev
   #:work-event-session-written-p
   #:event-digest-form
   #:event-record-form
   #:event-id
   #:closed-row-key
   #:payload-digest
   #:kind-fields
   ;; state
   #:make-seed-state
   #:state-open-count
   #:state-closed-count
   #:state-revision
   #:state-history
   #:state-closed-rows
   #:node-open-count
   #:node-branch
   #:node-state
   #:node-coordinator
   #:node-required-count
   #:node-required-open
   #:node-deps
   #:node-needs-broken
   #:ready-p
   #:ready-nodes
   #:node-estimate
   #:forecast
   #:node-holder
   #:state-lease-log
   #:take-lease
   #:release-lease
   #:working-count
   #:node-disposition
   #:roadmap-members
   #:roadmap-open
   #:node-title
   #:node-category
   #:node-links
   #:node-private
   #:node-version
   #:metadata-digest
   #:root-digest
   #:state-canonical-form
   #:reconstruct-state
   #:apply-event
   ;; instrumentation
   #:*visits* #:*parses* #:*replays*
   #:with-instrumentation
   ;; journal acceptance interface
   #:*before-apply-hook*
   #:journal-accept
   #:journal-record
   #:journal-lookup
   #:ordering-journal
   #:make-ordering-journal
   #:journal-order
   #:dedup-page-available-p
   #:rejecting-journal
   #:make-rejecting-journal
   #:journal-reject-on
   #:file-journal
   #:make-file-journal
   #:open-file-journal
   #:close-file-journal
   #:with-file-journal
   #:journal-fail-sync-on
   #:journal-fail-pre-write-on
   #:journal-fail-partial-write-on
   #:journal-fail-creation-sync-on
   #:replay-journal
   #:read-header
   #:read-record-frame
   #:journal-path
   #:journal-seq
   #:journal-uncertain-p
   #:sync-stream
   #:sync-directory
    ;; kernel
    #:make-kernel
    #:kernel-state
    #:kernel-journal
    #:kernel-next-rev
    #:submit
    #:ask-size
     #:open-issue-count
     #:open-leaf-count
    ;; state export / isolated load (SPEC-WORK.md:3273-3297, replays :5879-5905)
    #:export-state
    #:export-complete
    #:export-manifest
    #:state-export-id
    #:state-export-revision
    #:state-export-bytes
    #:state-export-members
    #:state-export-status
    #:state-export-terminal
    #:state-export-published
    #:publish-state-export
    #:cancel-state-export
    #:retention-pass
    #:load-state
    #:snapshot-state
    #:snapshot-revision
    #:snapshot-query
    #:snapshot-accept-session-p
    #:with-isolation
    #:isolation-count
    #:isolation-writes
    #:make-fenced-session
    #:fenced-export-start
    #:fenced-status
    #:fenced-cancel
    #:fenced-operation-list
    #:fenced-write
    #:fenced-claim
    ;; the fleet: static machine records in CONFIG (SPEC-WORK.md:3459-3588)
    #:make-fleet
    #:kernel-fleet
    #:fleet-friends
    #:fleet-machines
    #:fleet-order
    #:fleet-member
    #:fleet-members
    #:fleet-member-count
    #:machine
    #:machine-id
    #:machine-name
    #:machine-owner
    #:machine-connect
    #:machine-roles
    #:machine-permits
    #:machine-excludes
    #:machine-limits
    #:machine-facts
    ;; node verbs (nova-tools #362 replays)
    #:node-metadata
    #:node-edit
    #:node-undo
    #:node-edit-log
    #:render-node
    #:fetch-link
    #:*link-fetch-count*
    #:node-add
    #:node-repo
    #:repo-holder
    #:node-type
    #:node-view
    #:node-parent
    #:node-children
    #:roadmap-create
    #:node-move
    ;; applicable/delegation replays (Go card 8132)
    #:note-id
    #:make-note
    #:candidate-role
    #:candidate-model
    #:constraint-p
    #:constraint-deny
    #:constraint-prefer
    #:constraint-reason
    #:deny-matches-p
    #:constraint-excludes-p
    #:applicable
    #:make-applicable-answer
    #:applicable-answer-p
    #:applicable-answer-rev
    #:applicable-answer-from
    #:applicable-answer-verdicts
    #:applicable-answer-notes
    #:applicable-answer-fail
    #:applicable-answer-shown
    #:applicable-answer-more
    #:verdict-eligible-p
    #:verdict-unknown-p
    #:verdict-planning-p
    #:verdict-excluded-p
    #:excluded-note-ids
    #:price-route
    #:route-selection
    #:build-card
    #:*delegation-packet-fields*
    #:delegation-admission
    #:gate-2-refusal
    #:gate-3-refusal
    #:admission
    #:admission-expect
    #:gate-4-refusal
    #:offer-to
    #:non-terminating-p
    #:uncertain-outcome-p
    #:retry-permitted-p
    #:make-execution-record
    #:execution-record-requested-limit
    #:execution-record-expiry
    #:execution-record-stop
    #:make-machinery-receipt
    #:machinery-receipt-head
    #:machinery-receipt-result
    #:book-receipt
    #:review-binds-p
    #:review-reusable-p
    ;; CONFIG roles (SPEC-WORK.md:5214)
    #:make-role-record
    #:role-record-id
    #:role-record-scope
    #:role-record-source
    #:role-record-reserved-for
    #:role-record-essential-security-only-p
    #:role-record-different-perspective-p
    #:role-record-participation-p
    #:role-record-limit
    #:make-role-config
    #:role-config-roles
    #:role-from-config
    #:role-inferred-from-model-p
    #:agreed-limit-for
    #:spend-role
    ;; config/availability replays (card 8627)
    #:make-availability
    #:availability-state
    #:availability-last-contact
    #:availability-reserved
    #:availability-silence-threshold
    #:availability-answer-window
    #:availability-pinged
    #:silence-breach-p
    #:silence-ping
    #:mark-pinged
    #:mark-unconfirmed
    #:make-return-reconciliation
    #:return-reconciliation-assignments
    #:return-reconciliation-capacity
    #:return-reconciliation-done
    #:reconcile-return
    #:return-done-p
    #:dispatch-gate
    #:fragment-digest
    #:*config-fragment-keys*
    #:*config-secret-keys*
    #:make-config
    #:config-hash
    #:config-identity
    #:config-fragment
    #:make-delta-entry
    #:config-delta
    #:config-request
    #:apply-config-delta
    #:manifest-digest
    #:make-manifest
    #:find-secret
    #:admit-manifest
    ;; execution-control replay model (nova-tools #362)
   #:install-hold
   #:release-hold
   #:hold-for-scope
   #:hold-for-control
   #:dispatch-admitted-p
   #:race-admitted-p
   #:accept-offer
   #:reconcile-acceptance
   #:make-observation
   #:observation-attempt
   #:observation-outcome
   #:observation-usage
   #:synthesised-usage
   #:reconcile-observations
   #:release-permitted-p
   #:resume-workers
   #:resume-hold-kept-p
   #:unsupported-outcome
   #:correct-segment
   #:execution-correct
   #:bare-correct
    ;; closed-history replays (Go card 8601)
    #:make-closed-history
    #:closed-history-rows
    #:closed-history-page-records
    #:closed-history-page-bytes
    #:closed-history-root
    #:default-window-days
    #:window-days
    #:day-before
    #:stamp-day
    #:stamp-midnight-p
    #:merge-days-by-revision
    #:clip-day
    #:clip-day-batched
    #:query-history
    #:continue-query
    #:make-query-cursor
    #:query-cursor-root
    #:query-cursor-index
    #:query-cursor-days
    #:query-cursor-from
    #:query-cursor-to
    #:make-query-result
    #:query-result-shown
    #:query-result-pages
    #:query-result-more
    #:query-result-cursor
    #:query-result-days
    #:query-result-root
    #:query-result-read
    #:query-result-line
    #:query-result-expired
    #:index-depth
    #:make-history-cost
    #:history-cost
    #:history-cost-startup-resident-bytes
    #:history-cost-segment-bytes-read
    #:history-cost-parses
    #:history-cost-replays
    #:history-cost-emitted-bytes
    #:history-cost-index-pages-read
    #:history-cost-scanned-days
    #:history-cost-dedup-loads
    ;; publication, overlay and day coverage (replays of SPEC-WORK.md:716-762)
    #:publication
    #:make-publication
    #:pub-revision
    #:pub-snapshot-sha
    #:pub-closed-sha
    #:pub-dedup-sha
    #:pub-manifests
    #:pub-files
    #:verify-publication
    #:overlay
    #:make-overlay
    #:ov-pages
    #:ov-entries
    #:replay-overlay
    #:closed-entry
    #:make-closed-entry
    #:ce-rev
    #:ce-id
    #:ce-stamp
    #:closed-segment
    #:make-closed-segment
    #:seg-name
    #:seg-entries
    #:day-manifest
    #:make-day-manifest
    #:man-name
    #:man-refs
    #:manifest-for-day
    #:closed-day-selection
    ;; closed-history / clip / new-verb replays (card 8603)
    #:ask-state-as-of
    #:admit-record
    #:clip
    #:split-index-page
    ;; replays-slice-05: merged-is-not-distributed
    #:make-release-task
    #:release-task-id
    #:release-task-version
    #:release-task-deps
    #:release-task-branch
    #:release-task-settle-stamp
    #:make-finding
    #:finding-id
    #:finding-branch
    #:finding-disposition
    #:finding-evidence
    #:finding-landed
    #:finding-released
    #:disposition-row
    ;; replays-slice-05: ready-names-the-blocker-and-the-resolver
    #:make-ready-item
    #:ready-item-id
    #:ready-item-branch
    #:ready-item-deps
    #:ready-item-holder
    #:ready-item-responsible
    #:ready-row-id
    #:ready-row-ready
    #:ready-row-reason
    #:ready-row-resolver
    #:ready-rows
    ;; replays-slice-05: remove-settles-only-open-items
    #:node-remove
    ;; replays-slice-05: endpoint-is-local-and-private
    #:make-session-endpoint
    #:session-endpoint-directory
    #:session-endpoint-socket-path
    #:session-endpoint-directory-mode
    #:session-endpoint-socket-mode
    #:session-endpoint-owner
    #:session-endpoint-socket-family
    #:endpoint-network-listener-p
    #:local-socket-family
    #:current-account-uid
   ;; wire codec, protocol handshake, pipelined correlation, disconnect
   ;; reconciliation and the long-operation registry (nova-tools card 8608)
   #:wire-encode-integer
   #:wire-decode-value
   #:wire-number-token-p
   #:wire-object-decode
   #:wire-field
   #:make-protocol-session
   #:protocol-session-p
   #:protocol-session-supported
   #:protocol-session-version
   #:protocol-session-handshaken-p
   #:protocol-session-closed-p
   #:protocol-session-max-frame-bytes
   #:protocol-hello
   #:protocol-admit
   #:protocol-frame-ok-p
   #:protocol-framed-error
   #:make-wire-connection
   #:wire-connection-p
   #:wire-connection-protocol
   #:wire-connection-outstanding
   #:wire-connection-settled
   #:wire-connection-buffer
   #:wire-connection-closed-p
   #:wire-close
   #:wire-pipeline-request
   #:wire-feed
   #:wire-dispatch
   #:independent-batch-results
   #:atomic-batch-validate
   #:make-wire-session
   #:wire-session-p
   #:wire-session-kernel
   #:wire-session-pushed
   #:wire-session-client-alive-p
   #:wire-session-mutate
   #:make-operation-registry
   #:operation-registry-p
   #:operation-registry-operations
   #:operation-registry-journal
   #:operation-accept
   #:operation-state
   #:operation-complete
   #:operation-result
   #:operation-wait
   #:operation-client-exit
   #:operation-journal-length
   ;; the registry API renamed to keep it distinct from the operation struct
   ;; accessors added by card 8609 (operation-state/-result) and the session
   ;; operation-wait.
   #:registry-operation-state
   #:registry-operation-result
   #:registry-operation-wait
    ;; long operation, cancel, clip and undo/redo replays (card 8609)
    #:*operation-limits*
    #:make-operation
    #:operation-p
    #:operation-id
    #:operation-op
    #:operation-request
    #:operation-staged-bytes
    #:operation-retained-results
    #:make-work-session
    #:work-session-p
    #:work-session-operations
    #:work-session-events
    #:work-session-receipts
    #:work-session-limits
    #:work-session-git-timeout
    #:session-operation
    #:session-add-operation
    #:operation-status
    #:operation-pending-p
    #:session-bounded-p
    #:operation-cancel
    #:clip-request
    #:session-stop
    #:reconcile-operations
    #:*reversible-verbs*
    #:undo-request
    #:moved-preconditions
    #:redo-request
    ;; roadmap replays (card 8621)
    #:r8621-row-add #:r8621-row-finish #:r8621-row-retire
    #:r8621-row-active-count #:r8621-rows-export #:r8621-rows-load
    #:r8621-view-reopen
    #:r8621-matrix-make #:r8621-matrix-axis #:r8621-matrix-member-p
    #:r8621-matrix-retired-p #:r8621-matrix-remove #:r8621-matrix-restore
    #:r8621-matrix-add-axis #:r8621-matrix-flatten
    #:r8621-cfg-make #:r8621-cfg-value #:r8621-cfg-rev #:r8621-cfg-configure
    #:r8621-cfg-retry #:r8621-cfg-undo
    #:r8621-roadmap-make #:r8621-roadmap-settled-p #:r8621-roadmap-open-required
    #:r8621-roadmap-fold-count #:r8621-roadmap-metadata #:r8621-roadmap-project
    #:r8621-roadmap-render #:r8621-roadmap-add-member
    #:+r8621-marker-start+ #:+r8621-marker-end+
    #:r8621-render-body #:r8621-render-chat #:r8621-marker-region
    #:r8621-render-file
    ;; render replays (nova-tools #362)
    #:make-render-session
    #:render-session-p
    #:render-session-permissions
    #:render-session-mappings
    #:make-render-projection
    #:render-projection-p
    #:render-projection-repo
    #:render-projection-root
    #:render-projection-target
    #:render-result-p
    #:render-result-ok
    #:render-result-reason
    #:render-result-line
    #:render-result-artifact
    #:render-result-wrote
    #:path-within-p
    #:render-symlink-escape-p
    #:marker-refusal
    #:render-file
    #:render-chat
    #:*render-frame-bound*
    #:artifact-bytes-ok-p
    #:artifact-hash-ok-p
    #:artifact-valid-p
    #:render-correlated-batch
    #:acquire-render-lock
    #:*render-lock-guards-external-editor*
    ;; priority replays (nova-tools #362)
    #:priority-field
    #:priority-slot
    #:priority-no-effect-p
    #:priority-set
    #:priority-clear
    #:effective-priority
    #:priority-settle
    #:priority-reopen
    #:priority-event
    #:priority-only-moves-its-field-p
    #:priority-lessp
    #:ready-order
    #:priority-order-refusal
    #:priority-eligible-p
    #:priority-starts-nothing-p
    #:*priority-event-keys*
    ;; priority and captured-state export replays (nova-tools #362)
    #:+rank-ceiling+
    #:rank-atom-p
    #:make-priority-table
    #:priority-table
    #:priority-table-p
    #:priority-change-id
    #:effective-rank
    #:priority-undo
    #:priority-order
    #:priority-rows
    #:priority-page
    #:make-work-view
    #:work-view
    #:work-view-p
    #:work-view-who
    #:work-view-lease
    #:work-view-worker
    #:work-view-approval
    #:priority-grants-nothing-p
    #:make-export-capture
    #:export-capture
    #:export-capture-p
    #:export-capture-revision
    #:export-capture-base
    #:export-capture-end
    #:export-capture-records
    #:export-capture-bytes
    #:state-record
    #:capture-export
    #:validate-export
    #:operation-registry
    #:begin-operation
    #:operation
    #:operation-start
    #:operation-finish
    #:unrelated-mutation
    ;; the priority-and-export operation model renamed to keep it distinct
    ;; from the operation struct and the registry operations.
    #:priority-operation
    #:priority-operation-p
    #:priority-operation-registry
    #:priority-operation-registry-p
    #:make-priority-operation-registry
    #:priority-operation-record
    #:priority-operation-state
    #:priority-operation-start
    #:priority-operation-finish
    #:priority-operation-cancel
    #:priority-operation-wait
    #:priority-table-set
    #:priority-table-clear
    ;; attempts/capabilities/silence replays (card 8626)
    #:*capability-group-kinds*
    #:make-capability-group
    #:capability-group-p
    #:capability-group-id
    #:capability-group-kind
    #:capability-group-source
    #:capability-group-last-verified
    #:capability-group-availability
    #:capability-group-constraints
    #:capability-group-declared-support
    #:capability-group-runtime-verified
    #:capability-group-free-capacity
    #:capability-declared-support-p
    #:capability-runtime-verified-p
    #:capability-free-capacity
    #:capability-fields-collapse-p
    #:dispatch-fact
    #:dispatch-fact-p
    #:dispatch-fact-kind
    #:dispatch-fact-request
    #:dispatch-fact-node
    #:dispatch-fact-to
    #:dispatch-fact-state
    #:dispatch-fact-reserved
    #:dispatch-fact-declared
    #:copy-dispatch-fact
    #:dispatch-offer
    #:delivery-receipt
    #:acknowledgement
    #:accepted-ownership
    #:facts-collapsed-p
    #:pending-offer-p
    #:pending-offer-reserved
    #:pending-offer-declared
    #:offer-after-timeout
    #:dispatch-launched-p
    #:second-offer-admitted-p
    #:make-attempt
    #:attempt
    #:attempt-p
    #:attempt-id
    #:attempt-node
    #:attempt-requested-model
    #:attempt-observed
    #:attempt-usage
    #:attempt-observed-model
    #:append-attempt
    #:attempts-collapsed-p
    #:silence-action
    #:availability-after-window
    #:silence-verdict
    #:probe-outcome
    ;; fleet recommendation and the four assignment facts (Go card 8629)
    #:make-machine
    #:machine-id
    #:machine-name
    #:machine-owner
    #:machine-roles
    #:machine-permits
    #:machine-excludes
    #:machine-limits
    #:machine-facts
    #:machine-connect
    #:machine-excludes-p
    #:machine-admits-p
    #:make-fleet-session
    #:fleet-session-who
    #:fleet-session-leases
    #:make-fleet-ask
    #:fleet-ask-kind
    #:fleet-ask-rows
    #:fleet-ask-fail
    #:fleet-ask-lease
    #:fleet-ask-exit-code
    #:fleet-row
    #:fleet-for
    #:make-assignment-state
    #:assignment-state-who
    #:assignment-state-offers
    #:assignment-state-deliveries
    #:assignment-state-acceptances
    #:assignment-state-declines
    #:assignment-state-reservations
    #:assignment-state-leases
    #:assignment-state-attempts
    #:assignment-state-evidence
    #:assignment-state-completed
    #:assignment-state-node-state
    #:assignment-state-w
    #:assignment-state-responsible
    #:assignment-state-free-slots
    #:assignment-state-launches
    #:*session-written-fields*
    #:make-staged-input
    #:staged-input-bytes
    #:staged-input-result
    #:staged-input-valid-p
    #:staged-input-rev
    #:staged-input-reason
    #:stage-provenance
    #:session-written-field
    #:assignment-offer
    #:assignment-acknowledge
    #:assignment-decline
    #:session-status
    ;; assignment/execution-control replays (Go card 8630)
    #:make-leasebook
    #:leasebook-nodes
    #:leasebook-w
    #:leasebook-leases
    #:leasebook-holders
    #:leasebook-pending
    #:leasebook-reservations
    #:leasebook-evidence
    #:leasebook-completion
    #:leasebook-receipts
    #:leasebook-requests
    #:leasebook-generation
    #:leasebook-observed-models
    #:leasebook-effects
    #:leasebook-bindings
    #:leasebook-index-node
    #:leasebook-index-friend
    #:leasebook-offer
    #:leasebook-received
    #:leasebook-accepted
    #:leasebook-decline
    #:lease-until
    #:leasebook-expire
    #:leasebook-receipt
    ;; execution control: the durable hold, the capture, the dispatch barrier and
    ;; the cancellation edge (SPEC-WORK.md:3921-3980)
    #:kernel-controls
    #:kernel-holds
    #:kernel-offers
    #:record-attempt
    #:live-attempt-ids
    #:live-attempt-p
    #:attempt-generation
    #:attempt-live-p
    #:execution-stop
    #:execution-pause
    #:hold-p
    #:hold-id
    #:hold-action
    #:hold-scope
    #:hold-targets
    #:hold-directives
    #:hold-anchor
    #:hold-revision
    #:hold-span
    #:hold-manifest
    #:hold-released-p
    #:hold-durable-p
    #:hold-pin
    #:hold-covers-node-p
    #:held-p
    #:capture-manifest
    #:manifest-hold-id
    #:manifest-revision
    #:manifest-span
    #:manifest-target-ids
    #:manifest-content-hash
    #:recover-controls
    #:prepare-offer
    #:send-offer
    #:reconcile-offer
    #:offer-effect
    #:offer-lease-p
    #:offer-launched-p
    #:lease-count
    #:launch-count
    #:launch-attempt
    #:correct-attempt
    #:move-node
    #:request-cancel
    #:cancel-confirm
    #:cancel-requested-p
    #:goal-stop
    ;; control-plane verbs renamed to keep them distinct from the replay
    ;; kernel's clip / accept-offer / release-hold.
    #:ctl-clip
    #:ctl-accept-offer
    #:ctl-release-hold
    ;; regression receipts (card 8641)
    #:regression-receipt
    #:make-regression-receipt
    #:regression-receipt-p
    #:regression-receipt-criterion
    #:regression-receipt-revision-coverage
    #:regression-receipt-uncertainty
    #:regression-receipt-assertion
    #:regression-receipt-mutation
    #:assertion-holds-p
    #:regression-evidence-p
    #:green-badge-p
    ;; savepoint vs shared checkpoint (card 8641)
    #:savepoint
    #:make-savepoint
    #:savepoint-p
    #:savepoint-id
    #:savepoint-schema
    #:savepoint-local-revision
    #:savepoint-age
    #:checkpoint
    #:make-checkpoint
    #:checkpoint-p
    #:checkpoint-id
    #:checkpoint-shared-revision
    #:savepoint-is-not-shared-backup-p
    #:restore-open
    #:savepoint-report
    #:checkpoint-line
    ;; a stop across distributed work (card 8641)
    #:control-request
    #:make-control-request
    #:control-request-p
    #:control-request-kind
    #:control-request-request
    #:control-request-targets
    #:control-handle
    #:make-control-handle
    #:control-handle-p
    #:control-handle-target
    #:control-handle-request
    #:control-handle-delivered
    #:control-handle-acknowledged
    #:control-handle-reconciled
    #:control-handle-generation
    #:copy-control-handle
    #:blocked-question
    #:make-blocked-question
    #:blocked-question-p
    #:blocked-question-node
    #:blocked-question-question
    #:blocked-question-fallback
    #:blocked-question-persisted
    #:*control-kinds*
    #:control-kind-p
    #:distribute-control
    #:stop-reaches-p
    #:control-retry-identity
    #:apply-correction
    #:fallback-plan
    #:independent-tasks-stall-p
    ;; node add field order (card 8641)
    #:*node-add-structure-fields*
    #:*node-add-pre-fold-fields*
    #:node-add-field-value
    #:node-add-structure
    #:node-add-structure-keys
    #:node-add-pre-fold-structure
    #:node-add-digest
    #:node-add-digest-second
    #:write-node-add-value
    #:load-node-add-fixture
    ;; archive completeness (card 8641)
    #:*archive-gap-kinds*
    #:archive-gap
    #:make-archive-gap
    #:archive-gap-p
    #:archive-gap-kind
    #:archive-gap-detail
    #:archive-gap-source-issue
    #:archive-capture
    #:make-archive-capture
    #:archive-capture-p
    #:archive-capture-source-issue
    #:archive-capture-author
    #:archive-capture-gaps
    #:archive-gaps-explicit-p
    #:archive-absorbable-p
    #:author-retains-source-p
    ;; replays-8642: bounds-are-not-prompts
    #:launcher #:make-launcher
    #:launcher-input-bound #:launcher-output-bound
    #:launcher-deadline #:launcher-attempt-limit
    #:missing-hard-limits #:auto-dispatch-allowed-p
    #:deadline-handle #:admit-execution
    ;; replays-8642: batch-with-bounds-and-urgency
    #:batch-config #:make-batch-config
    #:batch-config-max-bytes #:batch-config-max-records #:batch-config-max-delay-ms
    #:packet-fragment #:make-packet-fragment
    #:packet-fragment-id #:packet-fragment-bytes #:packet-fragment-kind
    #:packet-fragment-dependencies #:packet-fragment-retry-of
    #:packet #:make-packet #:packet-manifest #:packet-fragments
    #:exhausted-bound #:within-bounds-p #:batch-unchanged-p #:validate-packet
    #:delay-applies-p #:dependencies-of #:retry-identity-of
    ;; replays-8642: async-operations
    #:operation-launch #:async-operation-cancel
    ;; replays-8642: batches-and-pipelines
    #:apply-atomic-batch #:apply-independent-batch
    ;; replays-8642: cache-aware-context-choice
    #:cache-price #:make-cache-price
    #:cache-price-input-rate #:cache-price-cache-read-rate #:cache-price-cache-write-rate
    #:cache-cost #:tiered-input-cost
    #:context-plan #:make-context-plan
    #:context-plan-hit-rate #:context-plan-retention-tokens
    #:context-plan-new-prefix-tokens #:context-plan-rebuild-tokens
    #:plan-cost
    #:refresh-admission #:make-refresh-admission
    #:refresh-admission-decision #:refresh-admission-adapter #:refresh-admission-evidence
    #:refresh-refusal #:refresh-allowed-p #:choose-context-plan
    ;; replays card 8643: dry run, cost lineage, compaction and copied journals
    #:make-replay-session
    #:preview-mutation
    #:apply-mutation
    #:join-cost-lineage
    #:compact-copies
    #:restore-copy
    #:start-over-copy
    #:join-experiment-cost
    ;; efficiency, adoption and goal replays (card 8644)
    #:prime
    #:make-checklist-item
    #:checklist-item-text
    #:checklist-item-independent-verification
    #:checklist-item-independent-worker
    #:checklist-item-explicit-dependency
    #:checklist-item-isolated-recovery
    #:materializes-node-p
    #:checklist-open-delta
    #:*default-max-attempts*
    #:attempts-tripped-p
    #:lease-admission
    #:*delegate-refused-actions*
    #:delegate-admission
    #:make-trial-result
    #:trial-result-prospective
    #:trial-result-baseline
    #:trial-result-coverage
    #:trial-result-quality
    #:trial-result-tolerances-matched
    #:adoption-verdict
    #:make-root-step-record
    #:root-step-record
    #:root-step-record-node
    #:root-step-record-steps
    #:step-record-count
    #:step-record-node-explosion
    #:make-next-trigger
    #:next-trigger-kind
    #:next-trigger-due
    #:make-waiting-item
    #:waiting-item-id
    #:waiting-item-trigger
    #:pulse-reexecutions
    #:make-goal-store
    #:snapshot-goal-store
    #:goal-store-scope
    #:goal-store-goal
    #:goal-store-node-state
    #:goal-store-rev
    #:goal-store-notes
    #:goal-store-history
    #:goal-store-dedup
    #:goal-stop-state
    #:goal-add-note
    #:goal-set
    #:goal-update
    #:goal-cancel
    #:goal-show
    ;; the goal-world verbs renamed to keep them distinct from the
    ;; efficiency-goal replay's goal-set/-update/-show.
    #:goal-world-set
    #:goal-world-update
    #:goal-world-show
    ;; replay-8645: the goal world, the historic tick and hostile-data intake
    #:make-goal-world
    #:goal-world-p
    #:goal-world-rev
    #:goal-world-nodes
    #:goal-world-goals
    #:goal-world-events
    #:goal-world-seen
    #:goal-world-scope-rev
    #:gw-state
    #:gw-branch
    #:gw-goal
    #:gw-state-to
    #:gw-cancel
    #:gw-accept-add
    #:last-event
    #:event-fields-keys
    #:own-fields-ok-p
    #:goal-check
    #:stop-field
    #:make-tick-record
    #:tick-record-p
    #:tick-record-id
    #:tick-record-pinned-rev
    #:tick-record-source-sha
    #:tick-record-scope
    #:tick-record-historic-tick
    #:tick-record-current-verification
    #:source-change
    #:make-intake-limits
    #:intake-limits-p
    #:intake-limits-max-depth
    #:intake-limits-max-bytes
    #:intake-limits-max-nodes
    #:*intake-visits*
    #:intake-scan
    #:hostile-intake
    #:archive-path-safe-p
    #:imported-prose-effect
   ;; replays-8646 (nova-tools card 8646)
   #:inventory-accounting
   #:make-inventory-accounting
   #:inventory-accounting-baseline
   #:inventory-denominator
   #:inventory-observe
   #:inventory-interval-deltas
   #:inventory-sustained-divergence-p
   #:inventory-report
   #:make-cost
   #:cost-record-measured-cash
   #:cost-record-marginal-cash
   #:cost-record-reference-token-cost
   #:cost-known-p
   #:local-inference-cost
   #:make-working-set
   #:working-set-reconciled-p
   #:w-take
   #:w-renew
   #:w-release
   #:w-member-p
   #:w-count
   #:w-reconstruction-equal-p
   #:w-advance-clock
   #:w-uncertain-retained-p
   #:w-live-lease-p
   #:w-ask
   #:make-source-capture
   #:capture-observe
   #:capture-note-mutation
   #:capture-versions
   #:capture-reconcile
   #:capture-consistent-claim
   #:source-version-value
   #:source-capture-reconciled-p
   #:make-dispatch-packet
   #:make-dispatch-route
   #:dispatch-gates
    ;; acceptance replays 8647: policy, price, quiet, intake, recovery
    #:make-efficiency-policy
    #:efficiency-policy-complete-p
    #:make-policy-store
    #:policy-store-policy
    #:policy-store-history
    #:policy-store-manifests
    #:policy-store-executions
    #:policy-store-rev
    #:policy-intake
    #:policy-store-export
    #:policy-store-import
    #:policy-undo
    #:policy-replay
    #:make-trial-manifest
    #:trial-manifest-id
    #:make-execution-reference
    #:execution-reference-policy-revision
    #:make-pricing-record
    #:pricing-record-id
    #:pricing-record-input
    #:pricing-record-effective-time
    #:make-pricing-registry
    #:register-pricing
    #:lookup-pricing
    #:pricing-refresh
    #:pricing-rate
    #:estimate-cost
    #:make-dispatch-pulse
    #:dispatch-pulse-record-bound
    #:dispatch-pulse-pending
    #:dispatch-pulse-pending-bytes
    #:dispatch-pulse-dispatches
    #:dispatch-pulse-flush
    #:observation-urgent-p
    #:observe-pulse
    #:make-recording-adapter
    #:adapter-inventory
    #:adapter-read
    #:adapter-read-calls
    #:adapter-mutation-calls
    #:adapter-mutate
    #:dry-run-capture
    #:initial-import
    #:apply-plan
    #:trial-stage
    #:trial-tolerances
    #:trial-fallback
    #:trial-tolerance-breach
    #:role-limits-within-p
    #:fallback-eligible-p
    #:make-assignment-control
    #:assignment-control-policy
    #:assignment-control-attempts
    #:assignment-control-handles
    #:assignment-control-suspended
    #:assignment-control-blocker
    #:automatic-assignment-allowed-p
    #:regression-recover
    #:assign-automatic))

(defpackage #:nova-work/tests
  (:use #:common-lisp #:nova-work)
  (:export #:run-all #:main))
