package main

import (
	"flag"
	"fmt"
	"os"
	"sort"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// This file holds the compatibility check the 2026-10-09 beat outage asked for:
// a build's client must be understood by the server of the release before it
// (docs/SPEC-SPRINT.md, "The client of this build is read by the last release's
// server"). The last release's verb table lives in
// testdata/last-release-verbs.golden, written from the last release tag by `make
// compat-verbs`; the test reads it and holds every verb and flag this build can
// send to it.

// compatGoldenPath is the recorded verb table of the last release, relative to
// the package directory (the test's working directory): a build's verbs and the
// flags each reads, one line a flag.
const compatGoldenPath = "testdata/last-release-verbs.golden"

// compatGoldenEnv names the file TestWriteCompatGolden writes; `make
// compat-verbs` sets it to the tree's copy while running the test in a worktree
// of the last release tag, so the table written is that release's.
const compatGoldenEnv = "NOVA_SPRINT_COMPAT_GOLDEN"

// compatGoldenHeader is the golden's first line, so a reader of the data file
// knows where it comes from and how to remake it.
const compatGoldenHeader = "nova-sprint verb table of the last release; generated by `make compat-verbs`"

// compatDeclaredAdditions are the verb and flag differences this client intends
// though the last release's server does not read them, each "verb" or "verb
// flag". A client-only flag is red unless it is a key here, since the server
// reads its flags by name and refuses one it does not know (the beat outage).
var compatDeclaredAdditions = map[string]string{}

// compatDeclaredRemovals are the verbs and flags the last release reads and this
// client no longer sends, each "verb" or "verb flag". A removal is safe for the
// server and red here only so that the intent is written down.
var compatDeclaredRemovals = map[string]string{}

// verbTable is a build's verbs and the flags each reads: verb, then flag name,
// then the kind of value the flag takes as flag.UnquoteUsage names it ("string",
// "int", "duration"; "bool" for a flag that takes none).
type verbTable map[string]map[string]string

// clientVerbTable reads this build's verb table from the verbs themselves
// (docs/SPEC-SPRINT.md, "The client of this build is read by the last release's
// server"): verbFlags runs each verb with --help and returns the flag set it
// built before it read or wrote anything, so the table is the code's own and
// never a hand list.
func clientVerbTable(t *testing.T) verbTable {
	t.Helper()
	table := make(verbTable, len(verbs))
	for _, v := range verbs {
		fs := verbFlags(v.name)
		require.NotNil(t, fs, "%s -h named no flag set: the verb did not reach its flags", v.name)
		flags := map[string]string{}
		fs.VisitAll(func(f *flag.Flag) {
			kind, _ := flag.UnquoteUsage(f)
			if kind == "" {
				kind = "bool"
			}
			flags[f.Name] = kind
		})
		table[v.name] = flags
	}
	return table
}

// String renders a table as the golden file: a header, then a line a flag,
// `<verb>\t<flag>\t<kind>`, verbs and flags in name order; a verb with no flags
// is one line `<verb>\t-\t-`.
func (t verbTable) String() string {
	var b strings.Builder
	b.WriteString("# " + compatGoldenHeader + "\n")
	names := make([]string, 0, len(t))
	for v := range t {
		names = append(names, v)
	}
	sort.Strings(names)
	for _, v := range names {
		flags := t[v]
		if len(flags) == 0 {
			fmt.Fprintf(&b, "%s\t-\t-\n", v)
			continue
		}
		fnames := make([]string, 0, len(flags))
		for f := range flags {
			fnames = append(fnames, f)
		}
		sort.Strings(fnames)
		for _, f := range fnames {
			fmt.Fprintf(&b, "%s\t%s\t%s\n", v, f, flags[f])
		}
	}
	return b.String()
}

// parseVerbTable reads the golden file's lines into a table, refusing a line a
// reader could not have written.
func parseVerbTable(t *testing.T, text string) verbTable {
	t.Helper()
	table := verbTable{}
	for n, line := range strings.Split(text, "\n") {
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		f := strings.Split(line, "\t")
		require.Len(t, f, 3, "%s line %d: want <verb>\\t<flag>\\t<kind>, got %q", compatGoldenPath, n+1, line)
		verb, name, kind := f[0], f[1], f[2]
		if table[verb] == nil {
			table[verb] = map[string]string{}
		}
		if name == "-" {
			require.Equal(t, "-", kind, "%s line %d: a verb with no flags is %q", compatGoldenPath, n+1, verb+"\t-\t-")
			continue
		}
		table[verb][name] = kind
	}
	return table
}

// compatDeclared reports whether key ("verb", or "verb flag") is a declared
// difference in the list.
func compatDeclared(list map[string]string, key string) bool {
	_, ok := list[key]
	return ok
}

// TestEveryVerbOfThisClientIsReadByTheLastRelease is the compatibility check: a
// verb or flag this build can send that the last release's server does not read
// is red, since the server refuses a word it does not know (the 2026-10-09 beat
// outage). The golden table is the last release's, and the only tolerated
// differences are the declared removals and additions
// (docs/SPEC-SPRINT.md, "The client of this build is read by the last release's
// server").
func TestEveryVerbOfThisClientIsReadByTheLastRelease(t *testing.T) {
	t.Parallel()
	raw, err := os.ReadFile(compatGoldenPath)
	require.NoError(t, err, "the last release's verb table is missing; run: make compat-verbs")
	last := parseVerbTable(t, string(raw))
	client := clientVerbTable(t)

	var problems []string
	// Every verb and flag this client can send must be read by the last
	// release's server; an addition is red unless it is declared.
	for verb, flags := range client {
		lastFlags, ok := last[verb]
		if !ok {
			if !compatDeclared(compatDeclaredAdditions, verb) {
				problems = append(problems, fmt.Sprintf("verb %q is new to this client and the last release's server does not read it; land the server first, or declare it in compatDeclaredAdditions", verb))
			}
			continue
		}
		for name, kind := range flags {
			lastKind, ok := lastFlags[name]
			if !ok {
				if !compatDeclared(compatDeclaredAdditions, verb+" "+name) {
					problems = append(problems, fmt.Sprintf("flag %s --%s is new to this client and the last release's server does not read it; land the server first, or declare it in compatDeclaredAdditions", verb, name))
				}
				continue
			}
			if !compatDeclared(compatDeclaredAdditions, verb+" "+name) {
				assert.Equalf(t, lastKind, kind, "flag %s --%s reads a %s here and a %s in the last release; the same word must parse the same on both, or declare it in compatDeclaredAdditions", verb, name, kind, lastKind)
			}
		}
	}
	// A verb or flag the last release reads and this client does not send is a
	// declared removal, written down so the change is intentional.
	for verb, flags := range last {
		clientFlags, ok := client[verb]
		if !ok {
			if !compatDeclared(compatDeclaredRemovals, verb) {
				problems = append(problems, fmt.Sprintf("verb %q of the last release is gone from this client; declare it in compatDeclaredRemovals", verb))
			}
			continue
		}
		for name := range flags {
			if _, ok := clientFlags[name]; !ok {
				if !compatDeclared(compatDeclaredRemovals, verb+" "+name) {
					problems = append(problems, fmt.Sprintf("flag %s --%s of the last release is gone from this client; declare it in compatDeclaredRemovals", verb, name))
				}
			}
		}
	}
	sort.Strings(problems)
	for _, p := range problems {
		t.Error(p)
	}
}

// TestWriteCompatGolden writes this build's verb table to the file
// $NOVA_SPRINT_COMPAT_GOLDEN and does nothing without it. `make compat-verbs`
// runs it in a worktree of the last release tag, so the file it writes is that
// release's table (docs/SPEC-SPRINT.md, "The client of this build is read by the
// last release's server").
func TestWriteCompatGolden(t *testing.T) {
	t.Parallel()
	out := os.Getenv(compatGoldenEnv)
	if out == "" {
		return
	}
	require.NoError(t, os.WriteFile(out, []byte(clientVerbTable(t).String()), 0o644))
}
