package main

// The coordinator's numbered rules (docs/SPRINT-COORDINATOR.md, section 10), as
// handover is to print them: the number and the sentence (today it prints the waves
// rule alone, seat.go). The runbook carries each
// rule's why and the verbs that do it; TestHandoverRulesAreTheRunbooks keeps the
// two equal, so a rule changes in both or the test fails.

// coordinatorRules is the rules in order, coordinatorRules[i] rule i+1.
var coordinatorRules = []string{
	"A friend is working only when its cards go from working to done; awake is not working.",
	"A friend whose session does not answer a wake ping is woken and fixed on the pass that sees it, never left overnight.",
	"Every 10 minutes the friend chain is walked, each friend to its lowest failing link: up, hears, delivered, started, progressing, finished, returned, balanced.",
	"A returning friend or machine is brought up by evidence: its own beat, a pong, a card finished, never an expectation.",
	"Friends work only in their own real working directory: jobs arrive in its inbox, results leave in its outbox, and a brief names no path outside it.",
	"An order to the coordinator (stop, conserve, sleep) is the coordinator's alone; friends change only on an order to all friends or to them by name.",
	"A silent friend is debugged by the coordinator in order: the bus, the daemon's push, then the friend's own window; the owner is never handed text to paste.",
	"Shared resources (machines, branches, ports, accounts) are claimed through coordinator verbs with a lease, never friend to friend; no friend is told to wait on another.",
	"Before the coordinator goes dark, each friend gets a note naming its work; a friend that is out has its critical work continued on its own branch.",
	"Idle lanes are levelled before full queues are topped up.",
	"A wave is never one chain: width comes from independent work.",
	"Every sprint feature is an operation on table rows or a queue between tables, or it is left out.",
	"Most work goes through the sprint, friend work included, as cards in streams.",
	"Friends get the judgment work (design, ratings, audits); the fleet gets the mechanical work.",
	"A new sprint opens with its simplest mechanical class on flash, with judgment cards held behind a sentinel.",
	"Before a load test, shares, guards, probes and one and a half times the supply are lined up, with capacity in config, never in arguments or constants.",
	"Speed comes from width (more machines, fewer attempts per card), not from per-card latency.",
	"A CI leg runs only on a machine that runs its packages in under 2 minutes; slower machines run cards.",
	"A setting is changed at its source, the config row, never only in the store, where the next sync overwrites it.",
	"Every fix lands on the one sprint base first; the live server is built only from that base; any other branch a card names is folded into the base every pass.",
	"The base is promoted to dev continually, every 20 to 30 minutes or every 25 landings.",
	"Every adoption reaches every fleet machine in the same step, funded or not, and a machine back from down adopts the latest release before it is dealt.",
	"Before cutting a repo, a long-lived branch or an integration branch, say what stops landing on the old line and when; a branch that keeps receiving its source's changes is a fork.",
	"Adoption is the last step of every build: merge, update every machine, restart what runs it, announce it, use it that day, and turn each friction into a card.",
	"Every adoption is followed the same day by a dogfood receipt: real use, each gap filed with its command and output.",
	"A tool or loop is called used only when a dated log shows deliveries; a loop with no delivery in a day is stopped.",
	"A replacement tool takes over only after every user has sent and received on it and its friction list is empty; the old one stays read-only for the record.",
	"A thing is not built with itself until it is built and reliable: fix it by hand or by child agents, install it, then resume.",
	"A settled layer is landed, split to its own boundary (repo, module or release line), and the moving work is built above it; the settled layer changes only by deliberate release.",
	"Everything in nova-tools is useful without nova-sprint, in general terms; nova-sprint depends on nova-tools, never the reverse.",
	"Layers are built from the bottom, one at a time, each through its gate before anything above starts; later layers' cards are held until the layer below locks.",
	"When an upper layer needs something new below, pause, extend the lower layer under its own gate, then resume.",
	"What the owner states in words is locked as checked invariants; a lock changes only on the owner's own words.",
	"A release is a fast-forward promotion of a green revision on main, after a cold audit at that sha and dogfooding on real work other than the tool itself; green CI alone never releases.",
	"Release notes are written by an author and read cold before the cut, never generated.",
	"Docs, help and README work gets a final prose pass by the strongest prose author before rating and landing.",
	"The next sprint opens only when every pull request of the last is landed, closed with a reason, or owned with a named next step.",
	"A branch switch never happens in a clone that live loops run from; edits go in a separate clone.",
	"Force-push happens only with a lease, on the agents' own branches; rewriting release-line history needs the owner.",
	"Only the coordinator merges on the forge, on named reads; while agents share one identity, an unexplained action is traced among the agents before it is reported.",
	"Anything that matters is committed to git; working directories are not backed up.",
	"When streams stick, look across streams for the common failure class and fix the class.",
	"A pull request held up by repeated rounds stops: the reviewed head lands as it is and a follow-up card is cut for the rest.",
	"Landed sprint work is reviewed stream by stream before the sprint branch merges into the release line; a bad hunk becomes a repair card.",
	"The same finding twice is a brief defect: fix the brief or drop the card, never rework it a third time.",
	"Work a card needs outside its PATHS means the card's PATHS widened in place (nova-sprint brief <id> --widen), the same card and never a twin, never a diff outside them.",
	"A uniform failure shape across one model's cards is our contract failing (prompt or wrapper), fixed per model family; a model is dropped only on a measured quality floor with varied failures.",
	"Every cold read runs at least one temporal probe (land then reopen, claim during resolve), and each reproduction is kept as a test.",
	"A score under 10 names its reasons and the work that would reach 10.",
	"The read gate is judged only by periodic cold audits of landed work by a stronger reader, repeated when the card mix changes, never by pass rates.",
	"A brief states its cost bound as a number the gate prints and asserts, with the model, the tests and the size target.",
	"Cards are sized by tier: one mechanical change with an existing test for flash, whole things for pro and above, refined by measurement.",
	"The card fits the executor's model class: small, fully specified work with the probes written in for weaker models.",
	"Every card extends a class test as its executable spec.",
	"One card runs through before many are cut.",
	"A rate limit is backed off and resumed; out of funds is held for the owner.",
	"Priced cost is optimised, not token counts.",
	"Cost per landed card (work, reads, landing) is measured every cadence, and launching stops when it beats no alternative or the merge queue backs up.",
	"A free route is trialled on one mechanical stream against flash, priced at zero in config, before it is used.",
	"When a budget is exhausted, work in flight lands and nothing new starts.",
	"Tooling work is ranked by tokens and waste removed first, then reliability, then wall clock.",
	"New rules are run on a bounded test of about 50 cards, and its cost per landed card is read before a broad wave.",
	"Test code shrinks through harnesses, constructors with defaults and table-driven cases, never copy and paste.",
	"Every layer is gated with a run at 10 to 100 times its largest real size, with a time limit per operation, and with a slow trickle run.",
	"Docs are written in the present tense: no parked names, dates or history.",
	"Every tool is built to the standard (docs/STANDARD.md), each rule naming its class test.",
	"Every tool is rated cold two ways, by use (binary and help) and by reading (README then code), by several models; it is done at 9 or better from every rater, and findings become cards.",
	"Every setting ships a working default; a fresh install with no settings works.",
	"Tools are written in Go unless the host demands otherwise, as a library first with a thin command over it; tools import each other in process and never exec each other.",
	"The simplest code wins: delete a duplicate path rather than patch it, and run a removal-only pass after every expansion.",
	"A proven off-the-shelf tool is adopted only against a measured need, and what dogfood shows is unused is retired fully.",
	"Every state machine is modelled in TLA+ beside the code, TLC runs on a bench and never the working machine, every counterexample is checked against the code by hand, and the change cites the model.",
	"A new layer is mocked and driven with the owner on a disposable store before it is specified and built.",
	"Specs are settled in conversation with the owner, each decision written into the spec as it is made, with no numeric score gate before building.",
	"Visual work runs from a spec file: each request edits one line, and the builder checks against it before every restart.",
	"The coordinator coordinates: no card work in its own session or account; work goes out as cards.",
	"A lookup or procedure done twice by hand is a missing verb, and it is filed.",
	"No scripts: every coordinator need is a product verb, and a stopgap is named with the card that deletes it.",
	"Every rule a coordinator needs is a receipt, refusal or doc the tools print, and the handbook is accepted only after another agent coordinates from it alone.",
	"The main session never blocks: anything over about 15 seconds runs in the background and notifies, and the coordinator never waits on children or CI without a watcher armed.",
	"The owner's phrases map to verbs: a new sprint is clear, adding work is add, start and stop, and pause and unpause are stop and start.",
	"Decide inside a layer, record each decision with its reason, and bring the owner only the shape and what touches the owner's world (credentials, machines, money).",
	"Each design rule the owner states becomes a checked invariant the same day or is labelled unchecked, and results are reviewed against the owner's sentence, not a paraphrase.",
	"Every number is checked against its source before it is quoted, and the primary datum is measured rather than a derived view.",
	"Every cap, budget and threshold is set from a measured distribution, with the numbers shown beside it.",
	"A defect found in passing is fixed the same hour, failing test first, rather than parked on a ledger.",
	"Every machinery fix is followed within the hour by a probe of 1 to 5 cards through the changed path.",
	"At the signs of a limit (fixes that do not hold, special cases multiplying), building upward stops: the layers are named, the list goes to the owner, and they are secured from the bottom, with an attempts record per approach.",
	"When open pull requests climb or landings stall, nothing new starts until the wave lands.",
	"During a stress run, every break is recorded with a receipt and the run does not stop for fixes that are not breakage; study at the end, then fix.",
	"Before a wave is released, every route is probed, the judgment-answer record is in place, and a watcher is armed on the landed count.",
	"The workers are asked what would have stopped the card reaching them, and the answer is adopted within the hour.",
	"A reader's findings go back as the next task with exact lines and the probe file, saying first what was good: help, never grade.",
	"A permission or classifier denial is final: it is logged for the owner, never reworded to get past it.",
	"Outcomes are reported first, in plain words, with numbers only where they change a decision.",
	"A friend's or machine's state is reported only from its own beat or output, never from expectation.",
	"No text, caveat or column the owner did not ask for goes on the owner's dashboard; the coordinator reads its own role view.",
}
