//go:build functional

package reconcile_test

import (
	"context"
	"strings"
	"testing"

	"github.com/mas-bandwidth/nova-tools/internal/nsprint/pitstop"
	"github.com/mas-bandwidth/nova-tools/internal/nsprint/reconcile"
	"github.com/mas-bandwidth/nova-tools/internal/nsprint/store"
	"github.com/mas-bandwidth/nova-tools/internal/nsprint/taskcard"
	"github.com/mas-bandwidth/nova-tools/internal/nsprint/ws/wstest"
)

// TestWaitingResolveReleasedStitchOneTrip (Stella's read of nova-tools
// #4449, 2026-09-27, her reproduction TestStellaReleasedStitchOneTrip:
// "waiting-resolve releasing one stitch takes 7 trips even with cached
// pitstop holds: the one move plus WriteStitchBrief's dependent reads/
// write"): a pass that releases a stitch is one round trip, the brief
// generated and written inside the call, and the released stitch's body
// starts with the whole picture.
func TestWaitingResolveReleasedStitchOneTrip(t *testing.T) {
	t.Parallel()
	_, c := wstest.Start(t)
	ctx := pitstop.WithHolds(context.Background(), nil)
	wrTask(t, c, "child", "landed", 1000, "where", "landed")
	wrTask(t, c, "plan", "waiting", 1001, "kind", "plan", "children", "child", "stitch", "join")
	wrTask(t, c, "join", "waiting", 2000, "blocked_on", "task:child", "phase", "stitch", "parent", "plan", "kind", "stitch")
	st := store.New(c)
	lease, err := reconcile.Acquire(ctx, st, reconcile.AcquireOptions{Host: "test"})
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() {
		if err := lease.Release(context.Background()); err != nil {
			t.Error(err)
		}
	})
	trips := st.CountTrips()
	lines, err := (&reconcile.WaitingResolve{Client: c}).Pass(ctx, lease)
	if err != nil {
		t.Fatal(err)
	}
	if trips.N() != 1 {
		t.Errorf("released stitch took %d trips; the budget is 1 (lines %+v)", trips.N(), lines)
	}
	if len(lines) != 1 || len(lines[0].Ready) != 1 || lines[0].Ready[0] != "join" {
		t.Fatalf("lines %+v, want join released", lines)
	}
	body, _ := c.HGet(ctx, taskcard.Key("join"), "body").Result()
	if !strings.Contains(body, taskcard.BriefMarker+" (generated by nova-sprint from the records; 1, stitch join)") || !strings.Contains(body, "- child landed") {
		t.Errorf("the released stitch's brief was not written in the call:\n%s", body)
	}
}
