#!/usr/bin/env bash
. "$HOME/rowan-working/bin/safe-rm.sh"
# flash-native-bench.sh (direct DeepSeek Flash) <bench> <seat> <card.md> <label>: run one Muse card via nova-swarm native ON a Linux bench over ssh (sandboxed, key by exec, retry on 5xx at start).
bench=$1; seat=$2; card=$3; label=$4; dl=${5:-1200}
# Arguments become part of a remote shell script and of paths: refuse anything that is not a plain name (pit stop 2026-09-17:
# a label of `../../evil; touch /tmp/x` ran its command on the bench). A refusal exits 2 before any ssh.
for _v in "$bench" "$seat" "$label"; do case "$_v" in ''|.|..|-*) echo "LAUNCH REFUSED: bad name '$_v'"; exit 2;; esac; printf %s "$_v" | grep -qE '^[A-Za-z0-9._-]+$' || { echo "LAUNCH REFUSED: bad name '$_v' (allowed: letters, digits, dot, underscore, dash)"; exit 2; }; done
case "$dl" in ''|*[!0-9]*) echo "LAUNCH REFUSED: deadline must be a number of seconds: '$dl'"; exit 2;; esac
[ -f "$card" ] && [ -r "$card" ] || { echo "LAUNCH REFUSED $bench $label: card file not readable: $card"; exit 2; }
ssh -n -o BatchMode=yes -o ConnectTimeout=8 "$bench" true 2>/dev/null || { echo "LAUNCH REFUSED $bench $label: bench UNREACHABLE over ssh"; exit 3; }
# capacity is mechanical (Glenn 2026-09-17): allowed = min(cores*1.5 - load1, (free_gb - 25)/2, memfree_gb/2); a launch refuses when allowed < 1, printing the numbers
cap=$(ssh -n -o BatchMode=yes "$bench" 'c=$(nproc); l=$(cut -d. -f1 /proc/loadavg); f=$(df -BG "$HOME" | awk '"'"'NR==2{gsub("G","",$4); print $4}'"'"'); m=$(awk '"'"'/MemAvailable/{printf "%d", $2/1048576}'"'"' /proc/meminfo); a1=$(( c*3/2 - l - c/8 )); a2=$(( (f-25)/2 )); a3=$(( m/2 )); a=$a1; [ $a2 -lt $a ] && a=$a2; [ $a3 -lt $a ] && a=$a3; echo "cores=$c load=$l free=${f}G memfree=${m}G allowed=$a"' 2>/dev/null); allowed=${cap##*allowed=}; [ "${allowed:-0}" -ge 1 ] 2>/dev/null || { echo "LAUNCH REFUSED $bench $label: CAPACITY $cap"; exit 2; }
{ echo "label=$label; seat=$seat; dl=$dl"; echo 'cat > /dev/null <<"CARDEND"'; echo CARDEND; cat <<'EOS'
export PATH=$HOME/.local/bin:$HOME/go/bin:$PATH; R=$HOME/rowan-working/tmp; S=$R/$(cat /proc/sys/kernel/random/uuid 2>/dev/null || uuidgen | tr A-Z a-z)-$label; H=$HOME/nova-bench/harness-v1.18.20/opencode
mkdir -p $R/cards; cat > $R/cards/$label.md
for attempt in 1 2 3; do [ -n "$label" ] && [ -n "$S" ] || exit 2; safe_rm "$S/jobs/$label"; mkdir -p "$S/jobs/$label"; (cd $S/jobs/$label && git init -q .); t0=$(date +%s)
  l=$(nova-secrets exec --store $HOME/nova-bench/secrets --as $seat --key $HOME/.config/nova-secrets/$seat.key --sops $HOME/.local/bin/sops --only DEEPSEEK_API_KEY --require DEEPSEEK_API_KEY -- timeout $((dl+100)) nova-swarm native --harness $H --model deepseek/deepseek-flash --label $label --card $R/cards/$label.md --slot $S --root $R --deadline ${dl}s 2>&1 | tail -1)
  wall=$(( $(date +%s)-t0 )); if [ $wall -le 15 ] && grep -qiE 'Unexpected server error|Internal server error|Invalid API key|err_[0-9a-f]{8}' $S/jobs/$label/harness-output.log 2>/dev/null; then echo "$(hostname) $label attempt=$attempt PROVIDER-5XX; backoff"; sleep $((5+attempt*10)); continue; fi
  echo "$(hostname) $label attempt=$attempt wall=${wall}s ${l:0:60}"; break; done
grep -E '^(BRANCH|red|green|files):' $S/jobs/$label/RESULT.md 2>/dev/null | cut -c1-160; git -C $S/jobs/$label/repo log --oneline -1 2>/dev/null | cut -c1-90
EOS
} > /dev/null
# simpler: ship the card via stdin and the script via a heredoc argument
ssh -o BatchMode=yes "$bench" "bash -c 'export PATH=\$HOME/.local/bin:\$HOME/go/bin:\$PATH; R=\$HOME/rowan-working/tmp; mkdir -p \$R; S=\$R/\$(cat /proc/sys/kernel/random/uuid)-$label; H=\$HOME/nova-bench/harness-v1.18.20/opencode; mkdir -p \$R/cards; cat > \$R/cards/$label.md; for attempt in 1 2 3; do . \$HOME/.local/bin/safe-rm.sh; safe_rm \$S/jobs/$label; mkdir -p \$S/jobs/$label; (cd \$S/jobs/$label && git init -q .); printf \"{\\\"permission\\\":{\\\"external_directory\\\":\\\"allow\\\"}}\\n\" > \$S/jobs/$label/opencode.json; t0=\$(date +%s); l=\$(nova-secrets exec --store \$HOME/nova-bench/secrets --as $seat --key \$HOME/.config/nova-secrets/$seat.key --sops \$HOME/.local/bin/sops --only DEEPSEEK_API_KEY --require DEEPSEEK_API_KEY -- timeout $((dl+100)) nova-swarm native --harness \$H --model deepseek/deepseek-flash --label $label --card \$R/cards/$label.md --slot \$S --root \$R --deadline ${dl}s 2>&1 | tail -1); wall=\$(( \$(date +%s)-t0 )); if [ \$wall -le 15 ] && grep -qiE \"Unexpected server error|Internal server error|Invalid API key|err_[0-9a-f]{8}\" \$S/jobs/$label/harness-output.log 2>/dev/null; then echo \"\$(hostname) $label attempt=\$attempt PROVIDER-5XX; backoff\"; sleep \$((5+attempt*10)); continue; fi; echo \"\$(hostname) $label attempt=\$attempt wall=\${wall}s \${l:0:60}\"; break; done; grep -E \"^(BRANCH|red|green|files):\" \$S/jobs/$label/RESULT.md 2>/dev/null | cut -c1-160; git -C \$S/jobs/$label/repo log --oneline -1 2>/dev/null | cut -c1-90'" < "$card" 2>/dev/null
