#!/usr/bin/env bash
# harvest-bench.sh <bench>: bring finished native jobs (RESULT.md newer than 6 h, BRANCH: rowan/*) from a bench into the Studio clone over ssh,
# push each branch from the Studio (github-rowan), open a PR to dev, print one line per job. The bench never needs push rights.
set -uo pipefail; b=$1; export GH_CONFIG_DIR=$HOME/.config/gh-rowan; C=$HOME/rowan-working/nova-tools
ssh -o BatchMode=yes $b 'for j in ~/rowan-swarm-root/*/jobs/*/ ~/rowan-working/tmp/*/jobs/*/; do j=${j%/}; r=$j/RESULT.md; [ -f "$r" ] || continue; [ -f $j/.harvested ] && continue; [ -n "$(find "$r" -mmin -360)" ] || continue; br=$(grep -m1 "^BRANCH:" "$r" | awk "{print \$2}"); case "$br" in rowan/*) ;; *) continue;; esac; [ "$(git -C $j/repo rev-parse --abbrev-ref HEAD 2>/dev/null)" = "$br" ] || continue; if [ "$(git -C $j/repo rev-list --count origin/dev..HEAD 2>/dev/null)" = 0 ]; then echo "NO-COMMIT $j $br" >&2; touch $j/.harvested; continue; fi; printf "%s\t%s\t%s\t%s\t%s\n" "$j" "$br" "$(git -C $j/repo rev-parse --short HEAD)" "$(git -C $j/repo remote get-url origin 2>/dev/null | sed -E "s#.*github.com[:/]##; s#\\.git\$##")" "$(head -1 "$r" | cut -c1-150)"; done' 2>/dev/null | while IFS=$'\t' read -r j br sha repo res; do
  case "$repo" in mas-bandwidth/nova-tools) C=$HOME/rowan-working/nova-tools; base=dev;; mas-bandwidth/schema) C=$HOME/rowan-working/schema; base=main;; *) echo "HARVEST SKIP $b $(basename $j) unknown repo $repo"; continue;; esac
  label=$(basename "$j"); git -C $C fetch -q origin "refs/heads/${br}:refs/remotes/origin/${br}" 2>/dev/null; if git -C $C fetch -q "ssh://$b/$j/repo" "+${br}:refs/harvest/${br}" 2>/dev/null; then
    if exp=$(git -C $C ls-remote origin "refs/heads/${br}" | cut -f1); perr=$(git -C $C push -q --force-with-lease="${br}:${exp}" origin "refs/harvest/${br}:refs/heads/${br}" 2>&1 >/dev/null); [ -z "$perr" ] || ! printf "%s" "$perr" | grep -qE "rejected|error:|fatal:"; then ssh -n -o BatchMode=yes $b "touch $j/.harvested" 2>/dev/null
      t=$(echo "$res" | sed 's/^RESULT: //' | cut -c1-110); n=$(gh pr list </dev/null -R "$repo" --head "$br" --state open --json number,headRefName -q ".[] | select(.headRefName==\"$br\") | .number" 2>/dev/null | head -1)
      [ -z "$n" ] && n=$(gh pr create </dev/null -R "$repo" --base "$base" --head "$br" --title "$t ($label, $b)" --body "$(printf '%s\n\nSwarm card %s on %s via nova-swarm native (sandboxed, key by nova-secrets exec). Red test first per RESULT.md on the job.\n\n🤖 Generated with [Claude Code](https://claude.com/claude-code)' "$res" "$label" "$b")" 2>&1 | grep -oE '[0-9]+$')
      echo "HARVEST $b $label $br $sha pr=$repo#$n"; else why=other; case "$perr" in *"merge queue"*) why=branch-in-merge-queue;; *"stale info"*|*"non-fast-forward"*) why=lease-lost-branch-moved;; *"rotected branch"*) why=protected-branch;; *"Permission"*|*"denied"*) why=permission;; esac; echo "HARVEST PUSH-FAIL $b $label $br reason=$why"; fi; else echo "HARVEST FETCH-FAIL $b $label $br"; fi; done
