#!/usr/bin/env bash
# rebase-loop.sh [ticks]: every 10 min, cut and run a rebase card on space for each DIRTY rowan/* PR that has no rebase card yet (marker in queue/rebase-auto/).
export GH_CONFIG_DIR=$HOME/.config/gh-rowan; Q=${REBASE_Q:-$HOME/rowan-working/queue/rebase-auto}; mkdir -p $Q; B=${REBASE_BIN:-$HOME/rowan-working/bin}; # REBASE_Q, REBASE_BIN, REBASE_TSV, REBASE_SLEEP are test seams (tests/rebase-marker.sh)
 n=$(( $(ls $Q 2>/dev/null | grep -c card-) + 8800 ))
PRE="You are a Go engineer resolving a rebase. Your working directory is the one printed by pwd at STEP 1; write everything under it: the clone at ./repo, notes at <working directory>/scratch/ using that absolute path. No push, no PR, no GitHub calls; the branch is pushed by the harvester from ./repo. Finish within 15 minutes."
for tick in $(seq 1 ${1:-6}); do
  gh pr list -R mas-bandwidth/nova-tools --state open --limit 300 --json number,mergeStateStatus,headRefName,headRefOid,title,createdAt -q '.[] | select(.mergeStateStatus=="DIRTY" and (.headRefName|startswith("rowan/replays-")|not) and (.headRefName|startswith("rowan/")) and .createdAt > "2026-09-17T02:00:00Z") | "\(.number)\t\(.headRefName)\t\(.headRefOid[0:12])\t\(.title[0:90])"' > ${REBASE_TSV:-$HOME/rowan-working/queue/control/dirty-now.tsv}
  batch=""; while IFS=$'\t' read -r num br head title; do [ -n "$num" ] || continue
    # The marker remembers the HEAD it cut a card for. Same head and still DIRTY: a card is in flight or failed, do not pile on.
    # A NEW head that is DIRTY again (it was rebased once and dev moved under it) gets a new card. The old marker was a bare
    # flag, so a PR that went dirty twice was never cut again (PR #977, 2026-09-17).
    [ -f $Q/pr-$num ] && [ "$(cat $Q/pr-$num 2>/dev/null)" = "$head" ] && continue; printf '%s' "$head" > $Q/pr-$num; c=$Q/card-$n.md
    printf 'RESULT: CARD-%s nova-tools PR #%s rebased onto dev with its conflicts resolved and its tests green: %s\n%s\nSTEP 1. pwd && mkdir -p scratch && { [ -d repo ] || git clone -q https://github.com/mas-bandwidth/nova-tools.git repo; } && cd repo && git fetch -q origin dev %s && git checkout -q -b %s origin/%s && git log --oneline -1 | cat && git rebase origin/dev 2>&1 | tail -3\nSTEP 2. Resolve every conflict so that BOTH survive: dev'"'"'s text (other PRs that landed) and this branch'"'"'s additions; in a spec or a Lisp test file keep both in document order and never drop a rule or a deftest; in Go keep both changes and make it compile. After each file: git add <file>; then GIT_EDITOR=true git rebase --continue. Repeat until the rebase finishes. Record the conflicted files in scratch/conflicts.txt (absolute path).\nSTEP 3. If Go files changed: test -z "$(gofmt -l .)" && go vet ./... 2>&1 | tail -3 && go test $(git diff --name-only origin/dev -- "*.go" | xargs -n1 dirname | sort -u | sed "s|^|./|" | tr "\\n" " ") 2>&1 | tail -6. If lisp/nova-work changed: (cd lisp/nova-work && ./run-tests.sh 2>&1 | tail -4). A red test in a touched package is fixed in this branch'"'"'s own files, never by deleting dev'"'"'s tests.\nSTEP 4. git log --oneline origin/dev..HEAD | cat && git status --short | head -5\nSTEP 5. Write RESULT.md (cd back to your working directory first): line 1 the RESULT line above; BRANCH: %s at <sha> in ./repo; REBASED: onto <dev sha>; conflicts: <files>; green: <the test tail, one line>. Nothing else.\n' "$n" "$num" "$title" "$PRE" "$br" "$br" "$br" "$br" > $c
    batch="$batch $c"; n=$((n+1)); done < ${REBASE_TSV:-$HOME/rowan-working/queue/control/dirty-now.tsv}
  cnt=$(echo $batch | wc -w | tr -d ' '); echo "$(date -u +%H:%MZ) rebase tick $tick: $cnt new rebase cards"
  [ "$cnt" != 0 ] && (for c in $batch; do echo "$c $(basename $c .md)"; done | xargs -P 4 -L 1 sh -c 'sleep $((RANDOM % 5)); '"$B"'/flash-native-bench.sh space swarm-space "$0" "$1" 900' 2>&1 | grep -E 'wall=|REBASED' | cut -c1-110)
  sleep ${REBASE_SLEEP:-600}; done
