#!/usr/bin/env bash
# status-page.sh: write one HTML page of the fleet's numbers (width per bench, capacity, queue, merged, loops) and push it to space:~/status/index.html, served on :8080.
export GH_CONFIG_DIR=$HOME/.config/gh-rowan; R=mas-bandwidth/nova-tools; out=$(mktemp); now=$(date -u +%Y-%m-%dT%H:%M:%SZ)
rows=""; down=""; live_total=0; for b in hulk vision space mini; do l=$(ssh -n -o BatchMode=yes -o ConnectTimeout=5 $b 'n=0; for j in $HOME/rowan-working/tmp/*/jobs/*/; do [ -f "$j/harness-output.log" ] && [ ! -f "$j/RESULT.md" ] && [ $(( ($(date +%s) - $(stat -c %Y "$j/harness-output.log")) / 60 )) -lt 15 ] && n=$((n+1)); done; c=$(nproc); l=$(cut -d. -f1 /proc/loadavg); f=$(df -BG "$HOME" | awk '"'"'NR==2{gsub("G","",$4); print $4}'"'"'); m=$(awk '"'"'/MemAvailable/{printf "%d", $2/1048576}'"'"' /proc/meminfo); a1=$(( c*3/2 - l )); a2=$(( (f-25)/2 )); a3=$(( m/2 )); a=$a1; [ $a2 -lt $a ] && a=$a2; [ $a3 -lt $a ] && a=$a3; echo "$n $c $l ${f} ${m} $a"' 2>/dev/null); if [ -z "$l" ]; then rows="$rows<tr><td>$b</td><td colspan=\"6\"><b>DOWN</b> (no answer over ssh in 5 s)</td></tr>"; down="$down $b"; set -- 0 0 0 0 0 0; else set -- $l; live_total=$((live_total + ${1:-0})); rows="$rows<tr><td>$b</td><td>$1</td><td>$2</td><td>$3</td><td>$4 GB</td><td>$5 GB</td><td>$6</td></tr>"; fi; done # a bench that does not answer says DOWN: a row of zeros read as an idle bench (pit stop 2026-09-17)
# The Studio (macOS, the coordination bench and the darwin CI leg): it drowned at load 147 on 2026-09-17 and no page showed it.
sl=$(sysctl -n vm.loadavg | awk '{printf "%d", $2}'); sc=$(sysctl -n hw.ncpu); sf=$(df -g "$HOME" | awk 'NR==2{print $4}'); sw=$(ps -axo command | grep -c '[R]unner.Worker'); so=$(ps -axo ppid,etime,comm | awk '$1==1 && ($3 ~ /tar$/ || $3 ~ /zsh$/ || $3 ~ /opencode$/) && ($2 ~ /-/ || $2 ~ /^[0-9]+:[0-9]+:[0-9]+$/)' | wc -l | tr -d ' ')
rows="$rows<tr><td>studio</td><td>ci=$sw</td><td>$sc</td><td>$sl</td><td>$sf GB</td><td>-</td><td>orphans=$so</td></tr>"
q=$(gh api graphql -f query='{repository(owner:"mas-bandwidth",name:"nova-tools"){mergeQueue(branch:"dev"){entries(first:50){nodes{pullRequest{number} state}}}}}' -q '.data.repository.mergeQueue.entries.nodes[]|"\(.pullRequest.number):\(.state[0:6])"' 2>/dev/null | tr '\n' ' '); m=$(gh pr list -R $R --state merged --limit 500 --json mergedAt -q '[.[]|select(.mergedAt > "2026-09-17T02:00:00Z")]|length' 2>/dev/null); dev=$(gh api repos/$R/commits/dev -q '.sha[0:8]' 2>/dev/null); devrun=$(gh run list -R $R --branch dev --workflow ci.yml --limit 1 --json status,conclusion -q '.[]|"\(.status) \(.conclusion)"' 2>/dev/null)
loops="harvest=$(ps -ef | grep -c '[h]arvest-loop.sh') sweep=$(ps -ef | grep -c '[s]weep-loop.sh') rebase=$(ps -ef | grep -c '[r]ebase-loop.sh') fill=$(ps -ef | grep -c '[f]ill-loop.sh') upgrade=$(ps -ef | grep -c '[n]ova-upgrade-loop')"
ready=$(ls "$HOME/rowan-working/queue/ready"/card-*.md 2>/dev/null | wc -l | tr -d ' '); hour=$(date -u -v-60M +%Y-%m-%dT%H:%M:%SZ); fin_h=$(awk -v h="$hour" '$1 >= h' "${STATUS_METRICS:-$HOME/rowan-working/queue/metrics.tsv}" 2>/dev/null | wc -l | tr -d ' '); launched_h=$(grep -c 'attempt=' "$HOME/rowan-working/queue/fill.log" 2>/dev/null); refused_h=$(grep -c 'REFUSED' "$HOME/rowan-working/queue/fill.log" 2>/dev/null); hyg_h=$(for b in hulk vision space mini; do ssh -n -o BatchMode=yes -o ConnectTimeout=5 $b "awk -v h='$hour' '\$1 >= h && (\$2==\"delete-job\" || \$2==\"delete-slot\" || \$2==\"reap\")' ~/hygiene.log 2>/dev/null | wc -l" 2>/dev/null; done | awk '{s+=$1} END{print s+0}'); qawait=$(echo "$q" | grep -o 'AWAITI' | wc -l | tr -d ' '); qqueued=$(echo "$q" | grep -o 'QUEUED' | wc -l | tr -d ' '); qunm=$(echo "$q" | grep -o 'UNMERG' | wc -l | tr -d ' ')
cat > "$out" <<H
<!doctype html><html><head><meta charset="utf-8"><meta http-equiv="refresh" content="60"><title>nova fleet</title><style>body{font-family:-apple-system,Helvetica,sans-serif;margin:24px;color:#222}table{border-collapse:collapse}td,th{border:1px solid #ccc;padding:4px 10px;text-align:right}th:first-child,td:first-child{text-align:left}pre{background:#f6f6f6;padding:8px}</style></head><body>
<h2>nova fleet at $now</h2>
<p>dev $dev, its run: $devrun. Merged into dev since 02:00Z: <b>$m</b>.</p>
<h3>queues</h3><table><tr><th>queue</th><th>depth</th><th>of which</th></tr>
<tr><td>merge queue</td><td>$(echo "$q" | wc -w | tr -d ' ')</td><td>running ${qawait:-0}, waiting ${qqueued:-0}, unmergeable ${qunm:-0}</td></tr>
<tr><td>ready cards (not yet launched)</td><td>$ready</td><td></td></tr>
<tr><td>launched by the fill loop, total</td><td>${launched_h:-0}</td><td>refused by capacity: ${refused_h:-0}</td></tr>
<tr><td>hygiene actions, last hour</td><td>${hyg_h:-0}</td><td>reaps and deletions across the benches</td></tr></table>
<h3>slots</h3>
<table><tr><th>bench</th><th>live cards</th><th>cores</th><th>load</th><th>free disk</th><th>free mem</th><th>allowed</th></tr>$rows</table>
<p>loops on the Studio: $loops</p>
<h3>time series (every minute)</h3><canvas id="c1" height="90"></canvas><canvas id="c2" height="90"></canvas>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/4.4.1/chart.umd.min.js"></script>
<script>fetch('metrics.tsv').then(r=>r.text()).then(t=>{const rows=t.trim().split('\n').map(l=>l.split('\t')).filter(r=>r.length>=6);const L=rows.map(r=>r[0].slice(11,16));const mk=(id,ds)=>new Chart(document.getElementById(id),{type:'line',data:{labels:L,datasets:ds},options:{animation:false,scales:{y:{beginAtZero:true}}}});mk('c1',[{label:'live cards',data:rows.map(r=>+r[1])},{label:'queue depth',data:rows.map(r=>+r[2])},{label:'PRs opened, last hour',data:rows.map(r=>+r[4])}]);mk('c2',[{label:'merged into dev since 02:00Z',data:rows.map(r=>+r[3])},{label:'cards launched by the fill loop (cumulative)',data:rows.map(r=>+r[5])}]);});</script>
<p>allowed = min(cores*1.5 - load, (free_gb - 25)/2, memfree_gb/2). Page rewritten every minute; refreshes itself every minute.</p>
</body></html>
H
qn=$(echo "$q" | wc -w | tr -d ' '); opened=$(gh pr list -R $R --state all --limit 400 --json createdAt -q '[.[]|select(.createdAt > "'$(date -u -v-60M +%Y-%m-%dT%H:%M:%SZ)'")]|length' 2>/dev/null); launched=$(grep -c 'attempt=' "$HOME/rowan-working/queue/fill.log" 2>/dev/null); printf '%s\t%s\t%s\t%s\t%s\t%s\t%s\n' "$now" "${live_total:-0}" "${qn:-0}" "${m:-0}" "${opened:-0}" "${launched:-0}" "$(echo "$rows" | grep -oE '<td>[0-9]+ GB</td><td>[0-9]+ GB' | sed -E 's/<td>([0-9]+) GB.*/\1/' | tr '\n' ',' | sed 's/,$//')" >> "${STATUS_METRICS:-$HOME/rowan-working/queue/metrics.tsv}"
scp -q "$out" space:status/index.html 2>/dev/null && scp -q "${STATUS_METRICS:-$HOME/rowan-working/queue/metrics.tsv}" space:status/metrics.tsv 2>/dev/null && echo "STATUS PAGE pushed $now" || echo "STATUS PAGE push failed"; rm -f "$out"
